coverage:
  status:
    project:
      default:
        target: 70%
        informational: true
    patch:
      default:
        target: 75%
        informational: true

comment:
  require_changes: true
  require_base: true
  require_head: true
  layout: "condensed_header, diff, files"

ignore:
  - "tests/**"
  - "benchmarks/**"
  - "samples/**"
  - "docs/**"
  - "src/Docs/**"
