using System.Reflection;
using ExpressiveSharp;
using ExpressiveSharp.Docs.PlaygroundModel.Webshop;
using ExpressiveSharp.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace ExpressiveSharp.Docs.Playground.Core.Services.Scenarios;

public sealed class WebshopScenario : IPlaygroundScenario
{
    public string Id => "webshop";

    public string Title => "Web shop";

    public string DefaultSnippet =>
        "db.Customers.Where(x => x.Email != null && x.Email.Length > 5).Select(x => x.Email)";

    public string? DefaultSetup => null;

    public string WrapperTemplate => """
        // <auto-generated />
        #nullable enable
        namespace ExpressiveSharp.Docs.Playground.Snippet;

        using System;
        using System.Linq;
        using System.Linq.Expressions;
        using ExpressiveSharp;
        using ExpressiveSharp.EntityFrameworkCore;
        using ExpressiveSharp.Docs.PlaygroundModel.Webshop;

        public static class __Snippet
        {
            public static IQueryable Run(IWebshopQueryRoots db)
                => /*__SNIPPET__*/;
        }

        /*__SETUP__*/
        """;

    public IReadOnlyList<Assembly> ReferenceAssemblies { get; } = new[]
    {
        typeof(IExpressiveQueryable<>).Assembly,
        typeof(ExpressiveAttribute).Assembly,
        typeof(ExpressiveDbSet<>).Assembly,
        typeof(DbContext).Assembly,
        typeof(RelationalQueryableExtensions).Assembly,
        typeof(WebshopDbContext).Assembly,
    };

    public IReadOnlyList<ScenarioRenderTarget> RenderTargets { get; } = new[]
    {
        new ScenarioRenderTarget(
            Id: "sqlite",
            Label: "EF + SQLite",
            OutputLanguage: "sql",
            Render: static (queryable, _) => queryable.ToQueryString())
        {
            GetQueryArgument = static instance => ((WebshopScenarioInstance)instance).SqliteRoots,
        },

        new ScenarioRenderTarget(
            Id: "postgres",
            Label: "EF + PostgreSQL",
            OutputLanguage: "sql",
            Render: static (queryable, _) => queryable.ToQueryString())
        {
            GetQueryArgument = static instance => ((WebshopScenarioInstance)instance).PostgresRoots,
            LazyLoadAssemblies = new[]
            {
                "Npgsql.dll",
                "Npgsql.EntityFrameworkCore.PostgreSQL.dll",
            },
        },
    };

    public IScenarioInstance CreateInstance() => new WebshopScenarioInstance();
}
