using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using ExpressiveSharp.Generator.Infrastructure;
using ExpressiveSharp.Generator.Models;
using ExpressiveSharp.Generator.SyntaxRewriters;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator;

/// <summary>
/// Source generator that intercepts calls to <c>IRewritableQueryable&lt;T&gt;</c> extension methods
/// that take <c>Func&lt;T,…&gt;</c> delegates (instead of <c>Expression&lt;Func&lt;T,…&gt;&gt;</c>).
/// For each such call-site it emits a <c>[InterceptsLocation]</c> method that rewrites the
/// lambda body through <see cref="ExpressionSyntaxRewriter"/> and forwards the result to the
/// matching <c>Queryable.*</c> overload.
///
/// Any extension method on <c>IRewritableQueryable&lt;T&gt;</c> that takes a <c>Func&lt;&gt;</c> is
/// intercepted by convention — including library-provided stubs and user-defined ones.
/// </summary>
[Generator]
public class PolyfillInterceptorGenerator : IIncrementalGenerator
{
    private const string IRewritableQueryableOpenTypeName =
        "ExpressiveSharp.IRewritableQueryable<T>";

    private const string PolyfillTypeName = "ExpressiveSharp.ExpressionPolyfill";
    private const string PolyfillMethodName = "Create";

    // ── IIncrementalGenerator ────────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Syntactic pre-filter: any member-access invocation with at least one argument
        // is a candidate. The semantic check in Emit does the real filtering.
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is InvocationExpressionSyntax inv &&
                inv.Expression is MemberAccessExpressionSyntax &&
                inv.ArgumentList.Arguments.Count > 0,
            transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node);

        var globalOptions = context.AnalyzerConfigOptionsProvider
            .Select(static (opts, _) => new ExpressiveGlobalOptions(opts.GlobalOptions));

        // Combine with the full compilation so we can do semantic analysis in the output step.
        context.RegisterSourceOutput(
            candidates.Collect().Combine(context.CompilationProvider).Combine(globalOptions),
            static (spc, pair) => Emit(pair.Left.Left, pair.Left.Right, pair.Right, spc));
    }

    // ── Emission ─────────────────────────────────────────────────────────────

    private static void Emit(
        ImmutableArray<InvocationExpressionSyntax> invocations,
        Compilation compilation,
        ExpressiveGlobalOptions globalOptions,
        SourceProductionContext spc)
    {
        var methodsBuilder = new StringBuilder();
        var snippetCount = 0;

        foreach (var inv in invocations)
        {
            spc.CancellationToken.ThrowIfCancellationRequested();

            try
            {
                var snippet = TryEmitPolyfill(inv, compilation, spc, snippetCount, globalOptions)
                           ?? TryEmit(inv, compilation, spc, snippetCount, globalOptions);
                if (snippet is not null)
                {
                    methodsBuilder.Append(snippet);
                    snippetCount++;
                }
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                // Report the failure so it doesn't hide bugs silently.
                // The stub body will throw UnreachableException at runtime with a clear message.
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.InterceptorEmissionFailed,
                    inv.GetLocation(),
                    ex.GetType().Name + ": " + ex.Message));
            }
        }

        if (snippetCount == 0) return;

        var methods = methodsBuilder.ToString();
        var source = $$"""
            // <auto-generated/>
            #nullable disable

            namespace ExpressiveSharp.Generated.Interceptors
            {
                internal static class PolyfillInterceptors
                {
            {{methods}}    }
            }

            namespace System.Runtime.CompilerServices
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data) { }
                }
            }
            """;

        spc.AddSource("PolyfillInterceptors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    // ── ExpressionPolyfill.Create() interception ──────────────────────────

    /// <summary>
    /// Detects calls to <c>ExpressionPolyfill.Polyfill&lt;TDelegate&gt;(lambda)</c> and emits
    /// an interceptor that returns a literal <c>Expression&lt;TDelegate&gt;</c> with the
    /// rewritten lambda body.
    /// </summary>
    private static string? TryEmitPolyfill(
        InvocationExpressionSyntax inv,
        Compilation compilation,
        SourceProductionContext spc,
        int index,
        ExpressiveGlobalOptions globalOptions)
    {
        var model = compilation.GetSemanticModel(inv.SyntaxTree);

        if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol method)
            return null;

        // Must be ExpressionPolyfill.Create<TDelegate>(...)
        if (method.Name != PolyfillMethodName)
            return null;
        if (method.ContainingType?.ToDisplayString() != PolyfillTypeName)
            return null;
        if (method.TypeArguments.Length != 1)
            return null;

        // First argument must be a lambda; optional second is params transformers
        if (inv.ArgumentList.Arguments.Count < 1)
            return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam)
            return null;
        var hasTransformers = method.Parameters.Length == 2;

        var interceptableLocation = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptableLocation(
            model, inv, spc.CancellationToken);
        if (interceptableLocation is null)
            return null;
        var interceptAttr = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(interceptableLocation);

        // Extract the delegate type — e.g., Func<Order, bool>
        var delegateType = method.TypeArguments[0];
        var delegateFqn = delegateType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Default to Rewrite (the whole point of Polyfill is enabling expression tree features),
        // but allow MSBuild global property to override.
        

        // Get the parameter types from the delegate to build Expression<TDelegate>
        // For Func<T1, T2, ..., TResult>, the lambda parameters map to T1..Tn
        if (delegateType is not INamedTypeSymbol delegateNamed || delegateNamed.TypeArguments.IsEmpty)
            return null;

        // Use the first type argument as the "element" type for the rewriter
        var elemType = delegateNamed.TypeArguments[0];
        if (elemType is not INamedTypeSymbol elemSymbol)
            return null;

        // Use ExpressionTreeEmitter to build the expression tree
        var exprTypeFqn = $"global::System.Linq.Expressions.Expression<{delegateFqn}>";
        var emitResult = EmitLambdaBody(lam, elemSymbol, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{index}_");
        if (emitResult is null)
            return null;

        if (hasTransformers)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::System.Linq.Expressions.Expression<{{delegateFqn}}> {{MethodId("Create", index)}}(
                        {{delegateFqn}} _,
                        params global::ExpressiveSharp.IExpressionTreeTransformer[] transformers)
                    {
            {{emitResult.Body}}            global::System.Linq.Expressions.Expression result = __lambda;
                        foreach (var t in transformers) result = t.Transform(result);
                        return (global::System.Linq.Expressions.Expression<{{delegateFqn}}>)result;
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::System.Linq.Expressions.Expression<{{delegateFqn}}> {{MethodId("Create", index)}}(
                    {{delegateFqn}} _)
                {
        {{emitResult.Body}}            return __lambda;
                }

        """;
    }

    // ── Per-invocation dispatch (IRewritableQueryable) ───────────────────────

    private static string? TryEmit(
        InvocationExpressionSyntax inv,
        Compilation compilation,
        SourceProductionContext spc,
        int index,
        ExpressiveGlobalOptions globalOptions)
    {
        var model = compilation.GetSemanticModel(inv.SyntaxTree);
        var ma = (MemberAccessExpressionSyntax)inv.Expression;

        // Receiver must be or implement IRewritableQueryable<T>.
        if (model.GetTypeInfo(ma.Expression).Type is not INamedTypeSymbol receiverType)
            return null;

        // Check both the type itself and its implemented interfaces
        if (!IsRewritableQueryable(receiverType))
            return null;

        if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol method)
            return null;

        // The stub convention: at least one non-receiver parameter must be a Func<> delegate,
        // not an Expression<Func<>>. This distinguishes user/library IRewritableQueryable<T> stubs
        // from regular IQueryable<T> extension methods.
        // For most methods, Func<> is Parameters[0]. For Join/GroupJoin/Zip/ExceptBy etc.,
        // it may be at a later position (e.g., Parameters[1]) after an IEnumerable<> arg.
        if (method.Parameters.IsEmpty) return null;
        int funcParamIndex = -1;
        int funcParamCount = 0;
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (method.Parameters[i].Type is INamedTypeSymbol pt &&
                pt.ConstructedFrom.Name == "Func" &&
                pt.ConstructedFrom.ContainingNamespace?.ToDisplayString() == "System")
            {
                funcParamCount++;
                if (funcParamIndex < 0)
                    funcParamIndex = i;
            }
        }
        if (funcParamIndex < 0) return null;

        // Get the interceptable location using the Roslyn 5.0+ API.
        // This produces the correct [InterceptsLocation(version, data)] attribute text.
        var interceptableLocation = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptableLocation(
            model, inv, spc.CancellationToken);

        if (interceptableLocation is null)
            return null;

        var interceptAttr = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(interceptableLocation);

        // Element type T of IRewritableQueryable<T>.
        // The receiver may be IRewritableQueryable<T> directly, or a type that implements it.
        var rewritableInterface = GetRewritableQueryableInterface(receiverType);
        if (rewritableInterface is null)
            return null;
        var elementType = rewritableInterface.TypeArguments[0];
        if (elementType is not INamedTypeSymbol elementSymbol)
            return null; // Skip when T is itself a type parameter
        var isAnonElement = elementSymbol.IsAnonymousType;

        var elementFqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodName = ma.Name.Identifier.Text;
        var typeArgs = method.TypeArguments;

        // Per-call WithExpressionRewrite() → MSBuild global → hardcoded Ignore fallback.

        // Resolve the target type for the Queryable.* call. Defaults to System.Linq.Queryable
        // unless overridden by [PolyfillTarget(typeof(...))] on the stub method.
        var targetTypeFqn = "global::System.Linq.Queryable";
        var polyfillAttr = method.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "PolyfillTargetAttribute");
        if (polyfillAttr?.ConstructorArguments.Length > 0 &&
            polyfillAttr.ConstructorArguments[0].Value is INamedTypeSymbol targetType)
        {
            targetTypeFqn = targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return methodName switch {
            "Where"
                when typeArgs.Length == 1
                => EmitWhere(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, globalOptions),

            "Select"
                when typeArgs.Length == 2 && method.Parameters.Length == 1
                    && method.Parameters[0].Type is INamedTypeSymbol selFuncType
                    && selFuncType.TypeArguments.Length == 3
                => EmitSelect(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, indexed: true),

            "Select"
                when typeArgs.Length == 2
                => EmitSelect(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions),

            "SelectMany"
                when typeArgs.Length == 2
                => EmitSelectMany2(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions),

            "SelectMany"
                when typeArgs.Length == 3
                => EmitSelectMany3(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], typeArgs[2], globalOptions),

            "OrderBy" or "OrderByDescending"
                when typeArgs.Length == 2 && method.Parameters.Length == 1
                => EmitOrdering(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs[1], ordered: false, globalOptions),

            "ThenBy" or "ThenByDescending"
                when typeArgs.Length == 2 && method.Parameters.Length == 1
                => EmitOrdering(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs[1], ordered: true, globalOptions),

            "GroupBy"
                when typeArgs.Length == 2 && method.Parameters.Length == 1
                => EmitGroupBy(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions),

            "GroupBy"
                when typeArgs.Length == 3
                => EmitGroupByMulti(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs, globalOptions),

            "GroupBy"
                when typeArgs.Length == 4
                => EmitGroupByMulti(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs, globalOptions),

            "Join" or "LeftJoin" or "RightJoin"
                when typeArgs.Length == 4
                => EmitJoin(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs, globalOptions),

            "GroupJoin"
                when typeArgs.Length == 4
                => EmitJoin(inv, model, spc, interceptAttr, index, "GroupJoin", elementSymbol, elementFqn, typeArgs, globalOptions),

            // Generic fallback: single-lambda stubs only. Multi-Func stubs (e.g., AggregateBy)
            // need dedicated emitters — the fallback would only rewrite the first Func<>,
            // leaving the rest as raw delegates which won't match Expression<Func<>> parameters.
            _ when funcParamCount == 1
                => EmitGenericSingleLambda(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, method, funcParamIndex, targetTypeFqn, globalOptions),

            _ => null, // Unsupported multi-Func stub — interceptor not generated, stub throws at runtime
        };
    }

    // ── Lambda helpers ───────────────────────────────────────────────────────

    /// <summary>
    /// Uses <see cref="Emitter.ExpressionTreeEmitter"/> to build the expression tree for a lambda body.
    /// Returns the emitter result containing imperative Expression.* factory code, or null on failure.
    /// </summary>
    private static Emitter.EmitResult? EmitLambdaBody(
        LambdaExpressionSyntax lambda,
        INamedTypeSymbol elementSymbol,

        SemanticModel model,
        SourceProductionContext spc,
        ExpressiveGlobalOptions globalOptions,
        string delegateTypeFqn,
        string assignToVariable = "__lambda",
        string varPrefix = "",
        IReadOnlyDictionary<ITypeSymbol, string>? typeAliases = null)
    {
        // For expression-bodied lambdas, use the expression directly.
        // For block-bodied lambdas, use the block.
        var bodyNode = lambda.Body is ExpressionSyntax expr ? (SyntaxNode)expr : lambda.Body;
        if (bodyNode is null) return null;

        var emitter = new Emitter.ExpressionTreeEmitter(model, spc, varPrefix: varPrefix);

        if (typeAliases is not null)
        {
            foreach (var kvp in typeAliases)
                emitter.RegisterTypeAlias(kvp.Key, kvp.Value);
        }

        var emitterParams = new List<Emitter.EmitterParameter>();
        if (lambda is SimpleLambdaExpressionSyntax simple)
        {
            var paramSymbol = model.GetDeclaredSymbol(simple.Parameter);
            var paramTypeFqn = (typeAliases is not null && typeAliases.TryGetValue(elementSymbol, out var elemAlias))
                ? elemAlias
                : elementSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            emitterParams.Add(new Emitter.EmitterParameter(
                simple.Parameter.Identifier.Text, paramTypeFqn,
                symbol: paramSymbol as IParameterSymbol));
        }
        else if (lambda is ParenthesizedLambdaExpressionSyntax parens)
        {
            foreach (var param in parens.ParameterList.Parameters)
            {
                var paramSymbol = model.GetDeclaredSymbol(param) as IParameterSymbol;
                var paramTypeFqn = paramSymbol?.Type is not null
                    ? (typeAliases is not null && typeAliases.TryGetValue(paramSymbol.Type, out var paramAlias)
                        ? paramAlias
                        : paramSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                    : "object";
                emitterParams.Add(new Emitter.EmitterParameter(
                    param.Identifier.Text, paramTypeFqn, symbol: paramSymbol));
            }
        }

        // Determine return type from delegate type args, resolving through aliases for anonymous types.
        var returnTypeFqn = "object";
        if (elementSymbol.ContainingNamespace is not null)
        {
            // Try to get the return type from the lambda's actual type info
            var typeInfo = model.GetTypeInfo(lambda);
            if (typeInfo.ConvertedType is INamedTypeSymbol convertedType &&
                convertedType.TypeArguments.Length > 0)
            {
                var returnTypeSymbol = convertedType.TypeArguments[convertedType.TypeArguments.Length - 1];
                if (typeAliases is not null && typeAliases.TryGetValue(returnTypeSymbol, out var aliasedReturn))
                    returnTypeFqn = aliasedReturn;
                else
                    returnTypeFqn = returnTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }

        var result = emitter.Emit(bodyNode, emitterParams, returnTypeFqn, delegateTypeFqn,
            assignToVariable: assignToVariable);

        // Prepend source comment showing the original lambda
        var sourceText = lambda.NormalizeWhitespace().ToFullString()
            .Replace("\r", "").Replace("\n", " ");
        var commentLine = $"            // Source: {sourceText}\n";
        return new Emitter.EmitResult(commentLine + result.Body);
    }

    // ── Type helpers ─────────────────────────────────────────────────────────

    /// <summary>
    /// Returns true if <paramref name="type"/> is an anonymous type, which cannot be
    /// named in C# source and requires a generic type parameter in the interceptor signature.
    /// </summary>
    private static bool IsAnonymousType(ITypeSymbol type)
        => type is INamedTypeSymbol { IsAnonymousType: true };

    // ── Formatting helpers ───────────────────────────────────────────────────

    private static string MethodId(string op, int index) => $"__Polyfill_{op}_{index}";

    // ── Per-operator emitters ────────────────────────────────────────────────
    // Each emitter returns a source snippet (or null on failure) using $$"""...""" raw string
    // literals. With two dollar signs: single { } are literal C# braces; {{expr}} interpolates.

    private static string? EmitWhere(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ExpressiveGlobalOptions globalOptions)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        var elemRef = ResolveRef(elemSym, "TElem", typeAliases);
        var hasAnon = typeAliases.Count > 0;
        var gp = GenericClause(typeAliases);

        var delegateFqn = $"global::System.Func<{elemRef}, bool>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{idx}_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> {{MethodId("Where", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Func<{{elemRef}}, bool> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Where(
                                (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                __lambda));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> {{MethodId("Where", idx)}}{{gp}}(
                    this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                    global::System.Func<{{elemRef}}, bool> _)
                {
        {{emitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Where(
                                (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelect(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol resultType,
        ExpressiveGlobalOptions globalOptions, bool indexed = false)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        if (elemSym.IsAnonymousType)
            typeAliases[elemSym] = "TElem";
        if (IsAnonymousType(resultType))
            typeAliases[resultType] = "TResult";
        var hasAnon = typeAliases.Count > 0;

        var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
        var resultRef = IsAnonymousType(resultType) ? "TResult" : resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var gp = hasAnon ? "<TElem, TResult>" : "";

        var idxPart = indexed ? "int, " : "";
        var delegateFqn = $"global::System.Func<{elemRef}, {idxPart}{resultRef}>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{idx}_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("Select", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Func<{{elemRef}}, {{idxPart}}{{resultRef}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Select(
                                (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                __lambda));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("Select", idx)}}{{gp}}(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, {{idxPart}}{{resultRef}}> _)
                {
        {{emitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Select(
                                (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelectMany2(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        if (elemSym.IsAnonymousType)
            typeAliases[elemSym] = "TElem";
        if (IsAnonymousType(resultType))
            typeAliases[resultType] = "TResult";
        var hasAnon = typeAliases.Count > 0;

        var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
        var resultRef = IsAnonymousType(resultType) ? "TResult" : resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var gp = hasAnon ? "<TElem, TResult>" : "";

        var delegateFqn = $"global::System.Func<{elemRef}, global::System.Collections.Generic.IEnumerable<{resultRef}>>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{idx}_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("SelectMany", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Func<{{elemRef}}, global::System.Collections.Generic.IEnumerable<{{resultRef}}>> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                __lambda));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("SelectMany", idx)}}{{gp}}(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, global::System.Collections.Generic.IEnumerable<{{resultRef}}>> _)
                {
        {{emitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelectMany3(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ITypeSymbol collType, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions)
    {
        if (inv.ArgumentList.Arguments.Count < 2) return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam2) return null;

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        if (elemSym.IsAnonymousType)
            typeAliases[elemSym] = "TElem";
        if (IsAnonymousType(collType))
            typeAliases[collType] = "TCollection";
        if (IsAnonymousType(resultType))
            typeAliases[resultType] = "TResult";
        var hasAnon = typeAliases.Count > 0;

        var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
        var collRef = IsAnonymousType(collType) ? "TCollection" : collType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var resultRef = IsAnonymousType(resultType) ? "TResult" : resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var gp = hasAnon ? "<TElem, TCollection, TResult>" : "";

        var delegateFqn1 = $"global::System.Func<{elemRef}, global::System.Collections.Generic.IEnumerable<{collRef}>>";
        var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1",
            varPrefix: $"i{idx}a_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult1 is null) return null;

        var delegateFqn2 = $"global::System.Func<{elemRef}, {collRef}, {resultRef}>";
        var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2",
            varPrefix: $"i{idx}b_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult2 is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("SelectMany", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Func<{{elemRef}}, global::System.Collections.Generic.IEnumerable<{{collRef}}>> _1,
                        global::System.Func<{{elemRef}}, {{collRef}}, {{resultRef}}> _2)
                    {
            {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                __lambda1,
                                __lambda2));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("SelectMany", idx)}}{{gp}}(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, global::System.Collections.Generic.IEnumerable<TCollection>> _1,
                    global::System.Func<TElem, TCollection, TResult> _2)
                {
        {{emitResult1.Body}}{{emitResult2.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                __lambda1,
                                __lambda2));
                }

        """;
    }

    private static string? EmitOrdering(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol keyType,
         bool ordered, ExpressiveGlobalOptions globalOptions)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        if (elemSym.IsAnonymousType)
            typeAliases[elemSym] = "TElem";
        if (IsAnonymousType(keyType))
            typeAliases[keyType] = "TKey";
        var hasAnon = typeAliases.Count > 0;

        var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
        var keyRef = IsAnonymousType(keyType) ? "TKey" : keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var gp = hasAnon ? "<TElem, TKey>" : "";

        var castFqn = ordered
            ? $"global::System.Linq.IOrderedQueryable<{elemRef}>"
            : $"global::System.Linq.IQueryable<{elemRef}>";

        var delegateFqn = $"global::System.Func<{elemRef}, {keyRef}>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{idx}_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Func<{{elemRef}}, {{keyRef}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})source,
                                __lambda));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TElem> {{MethodId(methodName, idx)}}{{gp}}(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TKey> _)
                {
        {{emitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TElem>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitGroupBy(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol keyType,
         ExpressiveGlobalOptions globalOptions)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        if (elemSym.IsAnonymousType)
            typeAliases[elemSym] = "TElem";
        if (IsAnonymousType(keyType))
            typeAliases[keyType] = "TKey";
        var hasAnon = typeAliases.Count > 0;

        var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
        var keyRef = IsAnonymousType(keyType) ? "TKey" : keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var gp = hasAnon ? "<TElem, TKey>" : "";

        var groupingFqn = $"global::System.Linq.IGrouping<{keyRef}, {elemRef}>";
        var delegateFqn = $"global::System.Func<{elemRef}, {keyRef}>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{idx}_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{groupingFqn}}> {{MethodId("GroupBy", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Func<{{elemRef}}, {{keyRef}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                __lambda));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<{{keyRef}}, TElem>> {{MethodId("GroupBy", idx)}}{{gp}}(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, {{keyRef}}> _)
                {
        {{emitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<{{keyRef}}, TElem>>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                __lambda));
                }

        """;
    }

    /// <summary>
    /// Multi-lambda emitter for GroupBy overloads with element/result selectors (arity 3 or 4).
    /// </summary>
    private static string? EmitGroupByMulti(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ImmutableArray<ITypeSymbol> typeArgs,
        ExpressiveGlobalOptions globalOptions)
    {
        // Arity 3: GroupBy<T, TKey, TElement>(keySelector, elementSelector) or
        //          GroupBy<T, TKey, TResult>(keySelector, resultSelector)
        // Arity 4: GroupBy<T, TKey, TElement, TResult>(keySelector, elementSelector, resultSelector)
        if (inv.ArgumentList.Arguments.Count < 2) return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam2) return null;

        if (typeArgs.Length == 3)
        {
            // Determine if this is element-selector or result-selector by checking 2nd lambda arity.
            var methodSym = (IMethodSymbol)model.GetSymbolInfo(inv).Symbol!;
            var secondFuncType = (INamedTypeSymbol)methodSym.Parameters[1].Type;
            var isElementSelector = secondFuncType.TypeArguments.Length == 2; // Func<T, TElement>

            var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
            if (elemSym.IsAnonymousType)
                typeAliases[elemSym] = "TElem";
            if (IsAnonymousType(typeArgs[1]))
                typeAliases[typeArgs[1]] = "TKey";
            if (IsAnonymousType(typeArgs[2]))
                typeAliases[typeArgs[2]] = "TThird";
            var hasAnon = typeAliases.Count > 0;

            var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
            var keyRef = IsAnonymousType(typeArgs[1]) ? "TKey" : typeArgs[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var thirdRef = IsAnonymousType(typeArgs[2]) ? "TThird" : typeArgs[2].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var gp = hasAnon ? "<TElem, TKey, TThird>" : "";

            var delegateFqn1 = $"global::System.Func<{elemRef}, {keyRef}>";
            var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1",
                varPrefix: $"i{idx}a_", typeAliases: hasAnon ? typeAliases : null);
            if (emitResult1 is null) return null;

            string delegateFqn2;
            if (isElementSelector)
                delegateFqn2 = $"global::System.Func<{elemRef}, {thirdRef}>";
            else
                delegateFqn2 = $"global::System.Func<{keyRef}, global::System.Collections.Generic.IEnumerable<{elemRef}>, {thirdRef}>";

            var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2",
                varPrefix: $"i{idx}b_", typeAliases: hasAnon ? typeAliases : null);
            if (emitResult2 is null) return null;

            if (!hasAnon)
            {
                if (isElementSelector)
                {
                    return $$"""
                            {{interceptAttr}}
                            internal static global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<{{keyRef}}, {{thirdRef}}>> {{MethodId("GroupBy", idx)}}(
                                this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                                global::System.Func<{{elemRef}}, {{keyRef}}> _1,
                                global::System.Func<{{elemRef}}, {{thirdRef}}> _2)
                            {
                    {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                    global::System.Linq.Queryable.GroupBy(
                                        (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                        __lambda1,
                                        __lambda2));
                            }

                    """;
                }
                else
                {
                    return $$"""
                            {{interceptAttr}}
                            internal static global::ExpressiveSharp.IRewritableQueryable<{{thirdRef}}> {{MethodId("GroupBy", idx)}}(
                                this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                                global::System.Func<{{elemRef}}, {{keyRef}}> _1,
                                global::System.Func<{{keyRef}}, global::System.Collections.Generic.IEnumerable<{{elemRef}}>, {{thirdRef}}> _2)
                            {
                    {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                    global::System.Linq.Queryable.GroupBy(
                                        (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                        __lambda1,
                                        __lambda2));
                            }

                    """;
                }
            }

            if (isElementSelector)
            {
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<{{keyRef}}, {{thirdRef}}>> {{MethodId("GroupBy", idx)}}{{gp}}(
                            this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                            global::System.Func<TElem, {{keyRef}}> _1,
                            global::System.Func<TElem, {{thirdRef}}> _2)
                        {
                {{emitResult1.Body}}{{emitResult2.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<{{keyRef}}, {{thirdRef}}>>)(object)
                                global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                    global::System.Linq.Queryable.GroupBy(
                                        (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                        __lambda1,
                                        __lambda2));
                        }

                """;
            }
            else
            {
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<{{thirdRef}}> {{MethodId("GroupBy", idx)}}{{gp}}(
                            this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                            global::System.Func<TElem, {{keyRef}}> _1,
                            global::System.Func<{{keyRef}}, global::System.Collections.Generic.IEnumerable<TElem>, {{thirdRef}}> _2)
                        {
                {{emitResult1.Body}}{{emitResult2.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{thirdRef}}>)(object)
                                global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                    global::System.Linq.Queryable.GroupBy(
                                        (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                        __lambda1,
                                        __lambda2));
                        }

                """;
            }
        }

        // Arity 4: GroupBy<T, TKey, TElement, TResult>(keySelector, elementSelector, resultSelector)
        if (typeArgs.Length == 4)
        {
            if (inv.ArgumentList.Arguments.Count < 3) return null;
            if (inv.ArgumentList.Arguments[2].Expression is not LambdaExpressionSyntax lam3) return null;

            var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
            if (elemSym.IsAnonymousType)
                typeAliases[elemSym] = "TElem";
            if (IsAnonymousType(typeArgs[1]))
                typeAliases[typeArgs[1]] = "TKey";
            if (IsAnonymousType(typeArgs[2]))
                typeAliases[typeArgs[2]] = "TElement";
            if (IsAnonymousType(typeArgs[3]))
                typeAliases[typeArgs[3]] = "TResult";
            var hasAnon = typeAliases.Count > 0;

            var elemRef = elemSym.IsAnonymousType ? "TElem" : elemFqn;
            var keyRef = IsAnonymousType(typeArgs[1]) ? "TKey" : typeArgs[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var elemSelRef = IsAnonymousType(typeArgs[2]) ? "TElement" : typeArgs[2].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resultRef = IsAnonymousType(typeArgs[3]) ? "TResult" : typeArgs[3].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var gp = hasAnon ? "<TElem, TKey, TElement, TResult>" : "";

            var delegateFqn1 = $"global::System.Func<{elemRef}, {keyRef}>";
            var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1",
                varPrefix: $"i{idx}a_", typeAliases: hasAnon ? typeAliases : null);
            if (emitResult1 is null) return null;

            var delegateFqn2 = $"global::System.Func<{elemRef}, {elemSelRef}>";
            var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2",
                varPrefix: $"i{idx}b_", typeAliases: hasAnon ? typeAliases : null);
            if (emitResult2 is null) return null;

            var delegateFqn3 = $"global::System.Func<{keyRef}, global::System.Collections.Generic.IEnumerable<{elemSelRef}>, {resultRef}>";
            var emitResult3 = EmitLambdaBody(lam3, elemSym, model, spc, globalOptions, delegateFqn3, "__lambda3",
                varPrefix: $"i{idx}c_", typeAliases: hasAnon ? typeAliases : null);
            if (emitResult3 is null) return null;

            if (!hasAnon)
            {
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("GroupBy", idx)}}(
                            this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                            global::System.Func<{{elemRef}}, {{keyRef}}> _1,
                            global::System.Func<{{elemRef}}, {{elemSelRef}}> _2,
                            global::System.Func<{{keyRef}}, global::System.Collections.Generic.IEnumerable<{{elemSelRef}}>, {{resultRef}}> _3)
                        {
                {{emitResult1.Body}}{{emitResult2.Body}}{{emitResult3.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                global::System.Linq.Queryable.GroupBy(
                                    (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                    __lambda1,
                                    __lambda2,
                                    __lambda3));
                        }

                """;
            }

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId("GroupBy", idx)}}{{gp}}(
                        this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                        global::System.Func<TElem, {{keyRef}}> _1,
                        global::System.Func<TElem, {{elemSelRef}}> _2,
                        global::System.Func<{{keyRef}}, global::System.Collections.Generic.IEnumerable<{{elemSelRef}}>, {{resultRef}}> _3)
                    {
            {{emitResult1.Body}}{{emitResult2.Body}}{{emitResult3.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}>)(object)
                            global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                global::System.Linq.Queryable.GroupBy(
                                    (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                    __lambda1,
                                    __lambda2,
                                    __lambda3));
                    }

            """;
        }

        return null;
    }

    /// <summary>
    /// Emitter for Join (and LeftJoin/RightJoin) with 3 lambdas and 1 forwarded IEnumerable argument.
    /// </summary>
    private static string? EmitJoin(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn,
        ImmutableArray<ITypeSymbol> typeArgs,
        ExpressiveGlobalOptions globalOptions)
    {
        // Arguments: [0] inner, [1] outerKeySelector, [2] innerKeySelector, [3] resultSelector
        if (inv.ArgumentList.Arguments.Count < 4) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[2].Expression is not LambdaExpressionSyntax lam2) return null;
        if (inv.ArgumentList.Arguments[3].Expression is not LambdaExpressionSyntax lam3) return null;

        var innerType = typeArgs[1];
        var keyType = typeArgs[2];
        var resultType = typeArgs[3];

        if (innerType is not INamedTypeSymbol innerSym) return null;

        var hasAnon = IsAnonymousType(innerType) || IsAnonymousType(keyType) || IsAnonymousType(resultType)
                      || elemSym.IsAnonymousType;

        // Anonymous path: ALL four type args become generic params so that the Queryable.Join
        // call's type inference can reconcile the method's generic params with the lambda types.
        // This differs from other emitters where only anonymous types get aliases.
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        string elemRef, innerRef, keyRef, resultRef;
        if (hasAnon)
        {
            typeAliases[elemSym] = "TOuter";
            typeAliases[innerType] = "TInner";
            typeAliases[keyType] = "TKey";
            typeAliases[resultType] = "TResult";
            elemRef = "TOuter";
            innerRef = "TInner";
            keyRef = "TKey";
            resultRef = "TResult";
        }
        else
        {
            elemRef = elemFqn;
            innerRef = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            keyRef = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            resultRef = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        // Lambda 1: outerKeySelector — Func<T, TKey>
        var delegateFqn1 = $"global::System.Func<{elemRef}, {keyRef}>";
        var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1",
            varPrefix: $"i{idx}a_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult1 is null) return null;

        // Lambda 2: innerKeySelector — Func<TInner, TKey>
        var delegateFqn2 = $"global::System.Func<{innerRef}, {keyRef}>";
        var emitResult2 = EmitLambdaBody(lam2, innerSym, model, spc, globalOptions, delegateFqn2, "__lambda2",
            varPrefix: $"i{idx}b_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult2 is null) return null;

        // Lambda 3: resultSelector — for non-anon, use the method symbol's parameter type
        // (captures GroupJoin's IEnumerable<TInner> shape); for anon, use constructed FQN.
        var resultSelectorFqn = !hasAnon
            && model.GetSymbolInfo(inv).Symbol is IMethodSymbol m && m.Parameters.Length > 3
                ? m.Parameters[3].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : $"global::System.Func<{elemRef}, {innerRef}, {resultRef}>";
        var emitResult3 = EmitLambdaBody(lam3, elemSym, model, spc, globalOptions, resultSelectorFqn, "__lambda3",
            varPrefix: $"i{idx}c_", typeAliases: hasAnon ? typeAliases : null);
        if (emitResult3 is null) return null;

        if (!hasAnon)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemRef}}> source,
                        global::System.Collections.Generic.IEnumerable<{{innerRef}}> inner,
                        global::System.Func<{{elemRef}}, {{keyRef}}> _1,
                        global::System.Func<{{innerRef}}, {{keyRef}}> _2,
                        {{resultSelectorFqn}} _3)
                    {
            {{emitResult1.Body}}{{emitResult2.Body}}{{emitResult3.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                (global::System.Linq.IQueryable<{{elemRef}}>)source,
                                inner,
                                __lambda1,
                                __lambda2,
                                __lambda3));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}> {{MethodId(methodName, idx)}}<TOuter, TInner, TKey, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TOuter> source,
                    global::System.Collections.Generic.IEnumerable<TInner> inner,
                    global::System.Func<TOuter, TKey> _1,
                    global::System.Func<TInner, TKey> _2,
                    global::System.Func<TOuter, TInner, TResult> _3)
                {
        {{emitResult1.Body}}{{emitResult2.Body}}{{emitResult3.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{resultRef}}>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                (global::System.Linq.IQueryable<{{elemRef}}>)(object)source,
                                inner,
                                __lambda1,
                                __lambda2,
                                __lambda3));
                }

        """;
    }

    /// <summary>
    /// Generic single-lambda emitter for user-defined stubs and future LINQ operators.
    /// Convention: the interceptor calls <c>Queryable.{methodName}</c> with the same name.
    /// The return type is taken from the stub's declared return type.
    /// Supports methods where the Func&lt;&gt; parameter is not necessarily at position 0
    /// (e.g., ExceptBy, Zip where the first parameter is IEnumerable&lt;T&gt;).
    /// Non-lambda parameters are forwarded directly to the Queryable.* call.
    /// </summary>
    private static string? EmitGenericSingleLambda(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn,
        IMethodSymbol method, int funcParamIndex, string targetTypeFqn,
        ExpressiveGlobalOptions globalOptions)
    {
        if (inv.ArgumentList.Arguments[funcParamIndex].Expression is not LambdaExpressionSyntax lam) return null;

        // Build the full Func<…> type string from the Func<> parameter.
        var funcTypeArgs = ((INamedTypeSymbol)method.Parameters[funcParamIndex].Type).TypeArguments;
        var hasAnyAnon = funcTypeArgs.Any(t => IsAnonymousType(t)) || elemSym.IsAnonymousType;

        // Determine if the stub returns IRewritableQueryable<X> (queryable) or a scalar type.
        var isRewritableReturn = method.ReturnType is INamedTypeSymbol rqType
            && rqType.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName;

        ITypeSymbol? returnElemType = null;
        if (isRewritableReturn)
        {
            returnElemType = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0];
            hasAnyAnon = hasAnyAnon || IsAnonymousType(returnElemType);
        }

        // For scalar returns, the FQN of the return type itself.
        var scalarReturnFqn = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // ThenBy/ThenByDescending require IOrderedQueryable<T>.
        var isOrdered = methodName is "ThenBy" or "ThenByDescending";

        // ── Shared: build type aliases, delegate FQN, param lists, emit lambda body ──
        var methodTypeArgs = method.TypeArguments;
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        string delegateFqn;
        string castFqn;
        string typeParams;
        string returnRef;
        string interceptorParamList;
        string queryableArgList;

        if (hasAnyAnon)
        {
            // All type args become generic params (T0, T1, …) for arity matching.
            var typeParamNames = new string[methodTypeArgs.Length];
            for (int i = 0; i < methodTypeArgs.Length; i++)
                typeParamNames[i] = $"T{i}";
            typeParams = $"<{string.Join(", ", typeParamNames)}>";

            if (elemSym.IsAnonymousType)
                typeAliases[elemSym] = typeParamNames[0];
            for (int i = 0; i < methodTypeArgs.Length; i++)
            {
                if (IsAnonymousType(methodTypeArgs[i]) && !typeAliases.ContainsKey(methodTypeArgs[i]))
                    typeAliases[methodTypeArgs[i]] = typeParamNames[i];
            }

            // Build generic Func<> — map each func type arg to T0, T1, etc.
            var funcArgStrings = new string[funcTypeArgs.Length];
            for (int i = 0; i < funcTypeArgs.Length; i++)
                funcArgStrings[i] = $"T{i}";
            var funcFqnGeneric = "global::System.Func<" + string.Join(", ", funcArgStrings) + ">";

            delegateFqn = "global::System.Func<" +
                string.Join(", ", funcTypeArgs.Select((t, i) =>
                    IsAnonymousType(t) ? funcArgStrings[i] : t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";

            castFqn = isOrdered
                ? $"global::System.Linq.IOrderedQueryable<{typeParamNames[0]}>"
                : $"global::System.Linq.IQueryable<{typeParamNames[0]}>";

            // Derive return type param name.
            if (isRewritableReturn)
            {
                var retElemIdx = -1;
                for (int i = 0; i < methodTypeArgs.Length; i++)
                {
                    if (SymbolEqualityComparer.Default.Equals(methodTypeArgs[i], returnElemType))
                    {
                        retElemIdx = i;
                        break;
                    }
                }
                returnRef = retElemIdx >= 0 ? typeParamNames[retElemIdx] : "T0";
            }
            else
            {
                returnRef = scalarReturnFqn;
            }

            // Build parameter and argument lists with Func<> using generic form.
            var interceptorParams = new List<string>();
            var queryableArgs = new List<string>();
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                if (i == funcParamIndex)
                {
                    interceptorParams.Add($"{funcFqnGeneric} _");
                    queryableArgs.Add("__lambda");
                }
                else
                {
                    var paramTypeFqn = method.Parameters[i].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var paramName = method.Parameters[i].Name;
                    interceptorParams.Add($"{paramTypeFqn} {paramName}");
                    queryableArgs.Add(paramName);
                }
            }
            interceptorParamList = string.Join(",\n                    ", interceptorParams);
            queryableArgList = string.Join(",\n                        ", queryableArgs);
        }
        else
        {
            typeParams = "";

            delegateFqn = "global::System.Func<" +
                string.Join(", ", funcTypeArgs.Select(t =>
                    t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";

            castFqn = isOrdered
                ? $"global::System.Linq.IOrderedQueryable<{elemFqn}>"
                : $"global::System.Linq.IQueryable<{elemFqn}>";

            returnRef = isRewritableReturn
                ? returnElemType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                : scalarReturnFqn;

            // Build parameter and argument lists with concrete Func<> type.
            var interceptorParams = new List<string>();
            var queryableArgs = new List<string>();
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                var paramTypeFqn = method.Parameters[i].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (i == funcParamIndex)
                {
                    interceptorParams.Add($"{paramTypeFqn} _");
                    queryableArgs.Add("__lambda");
                }
                else
                {
                    var paramName = method.Parameters[i].Name;
                    interceptorParams.Add($"{paramTypeFqn} {paramName}");
                    queryableArgs.Add(paramName);
                }
            }
            interceptorParamList = string.Join(",\n                    ", interceptorParams);
            queryableArgList = string.Join(",\n                        ", queryableArgs);
        }

        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn,
            varPrefix: $"i{idx}_", typeAliases: hasAnyAnon ? typeAliases : null);
        if (emitResult is null) return null;

        // ── Templates ──
        if (!hasAnyAnon)
        {
            if (isRewritableReturn)
            {
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<{{returnRef}}> {{MethodId(methodName, idx)}}(
                            this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                            {{interceptorParamList}})
                        {
                {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                {{targetTypeFqn}}.{{methodName}}(
                                    ({{castFqn}})source,
                                    {{queryableArgList}}));
                        }

                """;
            }

            return $$"""
                    {{interceptAttr}}
                    internal static {{returnRef}} {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        {{interceptorParamList}})
                    {
            {{emitResult.Body}}            return {{targetTypeFqn}}.{{methodName}}(
                                ({{castFqn}})source,
                                {{queryableArgList}});
                    }

            """;
        }

        if (isRewritableReturn)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{returnRef}}> {{MethodId(methodName, idx)}}{{typeParams}}(
                        this global::ExpressiveSharp.IRewritableQueryable<T0> source,
                        {{interceptorParamList}})
                    {
            {{emitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{returnRef}}>)(object)
                            global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                {{targetTypeFqn}}.{{methodName}}(
                                    ({{castFqn}})(object)source,
                                    {{queryableArgList}}));
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static {{returnRef}} {{MethodId(methodName, idx)}}{{typeParams}}(
                    this global::ExpressiveSharp.IRewritableQueryable<T0> source,
                    {{interceptorParamList}})
                {
        {{emitResult.Body}}            return {{targetTypeFqn}}.{{methodName}}(
                            ({{castFqn}})(object)source,
                            {{queryableArgList}});
                }

        """;
    }

    /// <summary>
    /// Returns true if <paramref name="type"/> is or implements <c>IRewritableQueryable&lt;T&gt;</c>.
    /// </summary>
    private static bool IsRewritableQueryable(INamedTypeSymbol type)
    {
        if (type.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName)
            return true;

        return type.AllInterfaces.Any(i =>
            i.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName);
    }

    /// <summary>
    /// Finds the <c>IRewritableQueryable&lt;T&gt;</c> interface on <paramref name="type"/>,
    /// or returns <paramref name="type"/> itself if it is <c>IRewritableQueryable&lt;T&gt;</c>.
    /// </summary>
    private static INamedTypeSymbol? GetRewritableQueryableInterface(INamedTypeSymbol type)
    {
        if (type.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName)
            return type;

        return type.AllInterfaces.FirstOrDefault(i =>
            i.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName);
    }

    /// <summary>
    /// If <paramref name="type"/> is an anonymous type, registers it in <paramref name="typeAliases"/>
    /// with the given <paramref name="alias"/> and returns the alias. Otherwise returns the FQN.
    /// </summary>
    private static string ResolveRef(
        ITypeSymbol type, string alias,
        Dictionary<ITypeSymbol, string> typeAliases)
    {
        if (type is INamedTypeSymbol { IsAnonymousType: true })
        {
            if (!typeAliases.ContainsKey(type))
                typeAliases[type] = alias;
            return alias;
        }
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    /// <summary>
    /// Returns "&lt;T1, T2&gt;" or "" if no aliases registered.
    /// </summary>
    private static string GenericClause(Dictionary<ITypeSymbol, string> typeAliases)
        => typeAliases.Count == 0 ? "" : "<" + string.Join(", ", typeAliases.Values) + ">";
}
