using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using ExpressiveSharp.Generator.Infrastructure;
using ExpressiveSharp.Generator.Models;
using ExpressiveSharp.Generator.SyntaxRewriters;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator;

/// <summary>
/// Source generator that intercepts calls to <c>IRewritableQueryable&lt;T&gt;</c> extension methods
/// that take <c>Func&lt;T,…&gt;</c> delegates (instead of <c>Expression&lt;Func&lt;T,…&gt;&gt;</c>).
/// For each such call-site it emits a <c>[InterceptsLocation]</c> method that rewrites the
/// lambda body through <see cref="ExpressionSyntaxRewriter"/> and forwards the result to the
/// matching <c>Queryable.*</c> overload.
///
/// Any extension method on <c>IRewritableQueryable&lt;T&gt;</c> that takes a <c>Func&lt;&gt;</c> is
/// intercepted by convention — including library-provided stubs and user-defined ones.
/// </summary>
[Generator]
public class PolyfillInterceptorGenerator : IIncrementalGenerator
{
    private const string IRewritableQueryableOpenTypeName =
        "ExpressiveSharp.IRewritableQueryable<T>";

    private const string PolyfillTypeName = "ExpressiveSharp.ExpressionPolyfill";
    private const string PolyfillMethodName = "Create";

    // ── IIncrementalGenerator ────────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Syntactic pre-filter: any member-access invocation with at least one argument
        // is a candidate. The semantic check in Emit does the real filtering.
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is InvocationExpressionSyntax inv &&
                inv.Expression is MemberAccessExpressionSyntax &&
                inv.ArgumentList.Arguments.Count > 0,
            transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node);

        var globalOptions = context.AnalyzerConfigOptionsProvider
            .Select(static (opts, _) => new ExpressiveGlobalOptions(opts.GlobalOptions));

        // Combine with the full compilation so we can do semantic analysis in the output step.
        context.RegisterSourceOutput(
            candidates.Collect().Combine(context.CompilationProvider).Combine(globalOptions),
            static (spc, pair) => Emit(pair.Left.Left, pair.Left.Right, pair.Right, spc));
    }

    // ── Emission ─────────────────────────────────────────────────────────────

    private static void Emit(
        ImmutableArray<InvocationExpressionSyntax> invocations,
        Compilation compilation,
        ExpressiveGlobalOptions globalOptions,
        SourceProductionContext spc)
    {
        var methodsBuilder = new StringBuilder();
        var allStaticFields = new List<string>();
        var snippetCount = 0;

        foreach (var inv in invocations)
        {
            spc.CancellationToken.ThrowIfCancellationRequested();

            try
            {
                var snippet = TryEmitPolyfill(inv, compilation, spc, snippetCount, globalOptions, allStaticFields)
                           ?? TryEmit(inv, compilation, spc, snippetCount, globalOptions, allStaticFields);
                if (snippet is not null)
                {
                    methodsBuilder.Append(snippet);
                    snippetCount++;
                }
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                // Report the failure so it doesn't hide bugs silently.
                // The stub body will throw UnreachableException at runtime with a clear message.
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.InterceptorEmissionFailed,
                    inv.GetLocation(),
                    ex.GetType().Name + ": " + ex.Message));
            }
        }

        if (snippetCount == 0) return;

        var staticFieldsBuilder = new StringBuilder();
        if (allStaticFields.Count > 0)
        {
            foreach (var f in allStaticFields)
            {
                staticFieldsBuilder.Append("        ").AppendLine(f);
            }
            staticFieldsBuilder.AppendLine();
        }
        var staticFieldsBlock = staticFieldsBuilder.ToString();
        var methods = methodsBuilder.ToString();
        var source = $$"""
            // <auto-generated/>
            #nullable disable

            namespace ExpressiveSharp.Generated.Interceptors
            {
                internal static class PolyfillInterceptors
                {
            {{staticFieldsBlock}}{{methods}}    }
            }

            namespace System.Runtime.CompilerServices
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data) { }
                }
            }
            """;

        spc.AddSource("PolyfillInterceptors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    // ── ExpressionPolyfill.Create() interception ──────────────────────────

    /// <summary>
    /// Detects calls to <c>ExpressionPolyfill.Polyfill&lt;TDelegate&gt;(lambda)</c> and emits
    /// an interceptor that returns a literal <c>Expression&lt;TDelegate&gt;</c> with the
    /// rewritten lambda body.
    /// </summary>
    private static string? TryEmitPolyfill(
        InvocationExpressionSyntax inv,
        Compilation compilation,
        SourceProductionContext spc,
        int index,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        var model = compilation.GetSemanticModel(inv.SyntaxTree);

        if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol method)
            return null;

        // Must be ExpressionPolyfill.Create<TDelegate>(...)
        if (method.Name != PolyfillMethodName)
            return null;
        if (method.ContainingType?.ToDisplayString() != PolyfillTypeName)
            return null;
        if (method.TypeArguments.Length != 1)
            return null;

        // First argument must be a lambda; optional second is params transformers
        if (inv.ArgumentList.Arguments.Count < 1)
            return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam)
            return null;
        var hasTransformers = method.Parameters.Length == 2;

        var interceptableLocation = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptableLocation(
            model, inv, spc.CancellationToken);
        if (interceptableLocation is null)
            return null;
        var interceptAttr = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(interceptableLocation);

        // Extract the delegate type — e.g., Func<Order, bool>
        var delegateType = method.TypeArguments[0];
        var delegateFqn = delegateType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Default to Rewrite (the whole point of Polyfill is enabling expression tree features),
        // but allow MSBuild global property to override.
        

        // Get the parameter types from the delegate to build Expression<TDelegate>
        // For Func<T1, T2, ..., TResult>, the lambda parameters map to T1..Tn
        if (delegateType is not INamedTypeSymbol delegateNamed || delegateNamed.TypeArguments.IsEmpty)
            return null;

        // Use the first type argument as the "element" type for the rewriter
        var elemType = delegateNamed.TypeArguments[0];
        if (elemType is not INamedTypeSymbol elemSymbol)
            return null;

        // Use ExpressionTreeEmitter to build the expression tree
        var exprTypeFqn = $"global::System.Linq.Expressions.Expression<{delegateFqn}>";
        var emitResult = EmitLambdaBody(lam, elemSymbol, model, spc, globalOptions, delegateFqn,
            fieldPrefix: $"i{index}_");
        if (emitResult is null)
            return null;

        allStaticFields.AddRange(emitResult.StaticFields);

        if (hasTransformers)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::System.Linq.Expressions.Expression<{{delegateFqn}}> {{MethodId("Create", index)}}(
                        {{delegateFqn}} _,
                        params global::ExpressiveSharp.IExpressionTreeTransformer[] transformers)
                    {
            {{emitResult.Body}}            global::System.Linq.Expressions.Expression result = __lambda;
                        foreach (var t in transformers) result = t.Transform(result);
                        return (global::System.Linq.Expressions.Expression<{{delegateFqn}}>)result;
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::System.Linq.Expressions.Expression<{{delegateFqn}}> {{MethodId("Create", index)}}(
                    {{delegateFqn}} _)
                {
        {{emitResult.Body}}            return __lambda;
                }

        """;
    }

    // ── Per-invocation dispatch (IRewritableQueryable) ───────────────────────

    private static string? TryEmit(
        InvocationExpressionSyntax inv,
        Compilation compilation,
        SourceProductionContext spc,
        int index,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        var model = compilation.GetSemanticModel(inv.SyntaxTree);
        var ma = (MemberAccessExpressionSyntax)inv.Expression;

        // Receiver must be or implement IRewritableQueryable<T>.
        if (model.GetTypeInfo(ma.Expression).Type is not INamedTypeSymbol receiverType)
            return null;

        // Check both the type itself and its implemented interfaces
        if (!IsRewritableQueryable(receiverType))
            return null;

        if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol method)
            return null;

        // The stub convention: at least one non-receiver parameter must be a Func<> delegate,
        // not an Expression<Func<>>. This distinguishes user/library IRewritableQueryable<T> stubs
        // from regular IQueryable<T> extension methods.
        // For most methods, Func<> is Parameters[0]. For Join/GroupJoin/Zip/ExceptBy etc.,
        // it may be at a later position (e.g., Parameters[1]) after an IEnumerable<> arg.
        if (method.Parameters.IsEmpty) return null;
        int funcParamIndex = -1;
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (method.Parameters[i].Type is INamedTypeSymbol pt &&
                pt.ConstructedFrom.Name == "Func" &&
                pt.ConstructedFrom.ContainingNamespace?.ToDisplayString() == "System")
            {
                funcParamIndex = i;
                break;
            }
        }
        if (funcParamIndex < 0) return null;

        // Get the interceptable location using the Roslyn 5.0+ API.
        // This produces the correct [InterceptsLocation(version, data)] attribute text.
        var interceptableLocation = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptableLocation(
            model, inv, spc.CancellationToken);

        if (interceptableLocation is null)
            return null;

        var interceptAttr = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(interceptableLocation);

        // Element type T of IRewritableQueryable<T>.
        // The receiver may be IRewritableQueryable<T> directly, or a type that implements it.
        var rewritableInterface = GetRewritableQueryableInterface(receiverType);
        if (rewritableInterface is null)
            return null;
        var elementType = rewritableInterface.TypeArguments[0];
        if (elementType is not INamedTypeSymbol elementSymbol)
            return null; // Skip when T is itself a type parameter
        if (elementSymbol.IsAnonymousType)
            return null; // Anonymous element types can't be named in the interceptor body

        var elementFqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodName = ma.Name.Identifier.Text;
        var typeArgs = method.TypeArguments;

        // Per-call WithExpressionRewrite() → MSBuild global → hardcoded Ignore fallback.
        

        return methodName switch {
            "Where"
                when typeArgs.Length == 1
                => EmitWhere(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, globalOptions, allStaticFields),

            "Select"
                when typeArgs.Length == 2
                => EmitSelect(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, allStaticFields),

            "SelectMany"
                when typeArgs.Length == 2
                => EmitSelectMany2(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, allStaticFields),

            "SelectMany"
                when typeArgs.Length == 3
                => EmitSelectMany3(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], typeArgs[2], globalOptions, allStaticFields),

            "OrderBy" or "OrderByDescending"
                when typeArgs.Length == 2
                => EmitOrdering(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs[1], ordered: false, globalOptions, allStaticFields),

            "ThenBy" or "ThenByDescending"
                when typeArgs.Length == 2
                => EmitOrdering(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs[1], ordered: true, globalOptions, allStaticFields),

            "GroupBy"
                when typeArgs.Length == 2
                => EmitGroupBy(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, allStaticFields),

            "GroupBy"
                when typeArgs.Length == 3
                => EmitGroupByMulti(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs, globalOptions, allStaticFields),

            "GroupBy"
                when typeArgs.Length == 4
                => EmitGroupByMulti(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs, globalOptions, allStaticFields),

            "Join" or "LeftJoin" or "RightJoin"
                when typeArgs.Length == 4
                => EmitJoin(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs, globalOptions, allStaticFields),

            "GroupJoin"
                when typeArgs.Length == 4
                => EmitGroupJoin(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs, globalOptions, allStaticFields),

            // Generic fallback: any user-defined or future single-lambda stub whose name
            // matches a Queryable.* method by convention.
            _ => EmitGenericSingleLambda(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, method, funcParamIndex, globalOptions, allStaticFields),
        };
    }

    // ── Lambda helpers ───────────────────────────────────────────────────────

    /// <summary>
    /// Uses <see cref="Emitter.ExpressionTreeEmitter"/> to build the expression tree for a lambda body.
    /// Returns the emitter result containing imperative Expression.* factory code, or null on failure.
    /// </summary>
    private static Emitter.EmitResult? EmitLambdaBody(
        LambdaExpressionSyntax lambda,
        INamedTypeSymbol elementSymbol,

        SemanticModel model,
        SourceProductionContext spc,
        ExpressiveGlobalOptions globalOptions,
        string delegateTypeFqn,
        string assignToVariable = "__lambda",
        string fieldPrefix = "",
        IReadOnlyDictionary<ITypeSymbol, string>? typeAliases = null)
    {
        if (lambda.Body is not SyntaxNode bodySyntax)
            return null;

        // For expression-bodied lambdas, use the expression directly.
        // For block-bodied lambdas, use the block.
        var bodyNode = lambda.Body is ExpressionSyntax expr ? (SyntaxNode)expr : lambda.Body;
        if (bodyNode is null) return null;

        var emitter = new Emitter.ExpressionTreeEmitter(model, spc, fieldPrefix);

        if (typeAliases is not null)
        {
            foreach (var kvp in typeAliases)
                emitter.RegisterTypeAlias(kvp.Key, kvp.Value);
        }

        var emitterParams = new List<Emitter.EmitterParameter>();
        if (lambda is SimpleLambdaExpressionSyntax simple)
        {
            var paramSymbol = model.GetDeclaredSymbol(simple.Parameter);
            var paramTypeFqn = elementSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            emitterParams.Add(new Emitter.EmitterParameter(
                simple.Parameter.Identifier.Text, paramTypeFqn,
                symbol: paramSymbol as IParameterSymbol));
        }
        else if (lambda is ParenthesizedLambdaExpressionSyntax parens)
        {
            foreach (var param in parens.ParameterList.Parameters)
            {
                var paramSymbol = model.GetDeclaredSymbol(param) as IParameterSymbol;
                var paramTypeFqn = paramSymbol?.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";
                emitterParams.Add(new Emitter.EmitterParameter(
                    param.Identifier.Text, paramTypeFqn, symbol: paramSymbol));
            }
        }

        // Determine return type from delegate type args, resolving through aliases for anonymous types.
        var returnTypeFqn = "object";
        if (elementSymbol.ContainingNamespace is not null)
        {
            // Try to get the return type from the lambda's actual type info
            var typeInfo = model.GetTypeInfo(lambda);
            if (typeInfo.ConvertedType is INamedTypeSymbol convertedType &&
                convertedType.TypeArguments.Length > 0)
            {
                var returnTypeSymbol = convertedType.TypeArguments[convertedType.TypeArguments.Length - 1];
                if (typeAliases is not null && typeAliases.TryGetValue(returnTypeSymbol, out var aliasedReturn))
                    returnTypeFqn = aliasedReturn;
                else
                    returnTypeFqn = returnTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }

        var result = emitter.Emit(bodyNode, emitterParams, returnTypeFqn, delegateTypeFqn,
            assignToVariable: assignToVariable);

        // Prepend source comment showing the original lambda
        var sourceText = lambda.NormalizeWhitespace().ToFullString()
            .Replace("\r", "").Replace("\n", " ");
        var commentLine = $"            // Source: {sourceText}\n";
        return new Emitter.EmitResult(commentLine + result.Body, result.StaticFields);
    }

    /// <summary>Returns the identifier text of the Nth parameter (0-based) of <paramref name="lambda"/>.</summary>
    private static string? ParamName(LambdaExpressionSyntax lambda, int index = 0) => lambda switch {
        SimpleLambdaExpressionSyntax s when index == 0 => s.Parameter.Identifier.Text,
        ParenthesizedLambdaExpressionSyntax p when p.ParameterList.Parameters.Count > index => p.ParameterList.Parameters[index].Identifier.Text,
        _ => null,
    };

    // ── Type helpers ─────────────────────────────────────────────────────────

    /// <summary>
    /// Returns true if <paramref name="type"/> is an anonymous type, which cannot be
    /// named in C# source and requires a generic type parameter in the interceptor signature.
    /// </summary>
    private static bool IsAnonymousType(ITypeSymbol type)
        => type is INamedTypeSymbol { IsAnonymousType: true };

    // ── Formatting helpers ───────────────────────────────────────────────────

    private static string MethodId(string op, int index) => $"__Polyfill_{op}_{index}";

    // ── Per-operator emitters ────────────────────────────────────────────────
    // Each emitter returns a source snippet (or null on failure) using $$"""...""" raw string
    // literals. With two dollar signs: single { } are literal C# braces; {{expr}} interpolates.

    private static string? EmitWhere(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, 
        ExpressiveGlobalOptions globalOptions, List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;
        var delegateFqn = $"global::System.Func<{elemFqn}, bool>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
        if (emitResult is null) return null;
        allStaticFields.AddRange(emitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> {{MethodId("Where", idx)}}(
                    this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                    global::System.Func<{{elemFqn}}, bool> _)
                {
        {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                        global::System.Linq.Queryable.Where(
                            (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                            __lambda));
                }

        """;
    }

    private static string? EmitSelect(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnon = IsAnonymousType(resultType);
        if (!isAnon)
        {
            var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = $"global::System.Func<{elemFqn}, {resultFqn}>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("Select", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{resultFqn}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Select(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda));
                    }

            """;
        }

        // Anonymous result type: must match arity 2 (T, TResult) of Select<T, TResult>.
        // TElem is generic in signature but concrete in body via (object) cast.
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default)
        {
            { resultType, "TResult" }
        };
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, TResult>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_", typeAliases: typeAliases);
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("Select", idx)}}<TElem, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TResult> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Select(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelectMany2(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnon = IsAnonymousType(resultType);
        if (!isAnon)
        {
            var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{resultFqn}>>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("SelectMany", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, global::System.Collections.Generic.IEnumerable<{{resultFqn}}>> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda));
                    }

            """;
        }

        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default)
        {
            { resultType, "TResult" }
        };
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<TResult>>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_", typeAliases: typeAliases);
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("SelectMany", idx)}}<TElem, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, global::System.Collections.Generic.IEnumerable<TResult>> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelectMany3(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ITypeSymbol collType, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments.Count < 2) return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam2) return null;

        var collFqn = collType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var hasAnon = IsAnonymousType(collType) || IsAnonymousType(resultType);
        if (!hasAnon)
        {
            var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn1 = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{collFqn}>>";
            var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_");
            if (emitResult1 is null) return null;
            allStaticFields.AddRange(emitResult1.StaticFields);

            var delegateFqn2 = $"global::System.Func<{elemFqn}, {collFqn}, {resultFqn}>";
            var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_");
            if (emitResult2 is null) return null;
            allStaticFields.AddRange(emitResult2.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("SelectMany", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, global::System.Collections.Generic.IEnumerable<{{collFqn}}>> _1,
                        global::System.Func<{{elemFqn}}, {{collFqn}}, {{resultFqn}}> _2)
                    {
            {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda1,
                                __lambda2));
                    }

            """;
        }

        // Arity 3: <TElem, TCollection, TResult>. All become generic to match SelectMany<T, TCollection, TResult>.
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        if (IsAnonymousType(collType))
            typeAliases[collType] = "TCollection";
        if (IsAnonymousType(resultType))
            typeAliases[resultType] = "TResult";

        var collRef = IsAnonymousType(collType) ? "TCollection" : collFqn;
        var anonDelegateFqn1 = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{collRef}>>";
        var anonEmitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, anonDelegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_", typeAliases: typeAliases);
        if (anonEmitResult1 is null) return null;
        allStaticFields.AddRange(anonEmitResult1.StaticFields);

        var resultRef = IsAnonymousType(resultType) ? "TResult" : resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var anonDelegateFqn2 = $"global::System.Func<{elemFqn}, {collRef}, {resultRef}>";
        var anonEmitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, anonDelegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_", typeAliases: typeAliases);
        if (anonEmitResult2 is null) return null;
        allStaticFields.AddRange(anonEmitResult2.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("SelectMany", idx)}}<TElem, TCollection, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, global::System.Collections.Generic.IEnumerable<TCollection>> _1,
                    global::System.Func<TElem, TCollection, TResult> _2)
                {
        {{anonEmitResult1.Body}}{{anonEmitResult2.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda1,
                                __lambda2));
                }

        """;
    }

    private static string? EmitOrdering(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol keyType,
         bool ordered, ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnonKey = IsAnonymousType(keyType);

        // ThenBy/ThenByDescending require IOrderedQueryable<T>; wrapper implements it.
        var castFqn = ordered
            ? $"global::System.Linq.IOrderedQueryable<{elemFqn}>"
            : $"global::System.Linq.IQueryable<{elemFqn}>";

        if (!isAnonKey)
        {
            var keyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = $"global::System.Func<{elemFqn}, {keyFqn}>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{keyFqn}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})source,
                                __lambda));
                    }

            """;
        }

        // Arity 2: <TElem, TKey>. Return type stays concrete (element type).
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default)
        {
            { keyType, "TKey" }
        };
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, TKey>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_", typeAliases: typeAliases);
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TElem> {{MethodId(methodName, idx)}}<TElem, TKey>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TKey> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TElem>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitGroupBy(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol keyType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnonKey = IsAnonymousType(keyType);
        if (!isAnonKey)
        {
            var keyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var groupingFqn = $"global::System.Linq.IGrouping<{keyFqn}, {elemFqn}>";
            var delegateFqn = $"global::System.Func<{elemFqn}, {keyFqn}>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{groupingFqn}}> {{MethodId("GroupBy", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{keyFqn}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda));
                    }

            """;
        }

        // Arity 2: <TElem, TKey>. Return type is IGrouping<TKey, TElem>.
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default)
        {
            { keyType, "TKey" }
        };
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, TKey>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_", typeAliases: typeAliases);
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<TKey, TElem>> {{MethodId("GroupBy", idx)}}<TElem, TKey>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TKey> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<TKey, TElem>>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda));
                }

        """;
    }

    /// <summary>
    /// Multi-lambda emitter for GroupBy overloads with element/result selectors (arity 3 or 4).
    /// </summary>
    private static string? EmitGroupByMulti(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ImmutableArray<ITypeSymbol> typeArgs,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        // Arity 3: GroupBy<T, TKey, TElement>(keySelector, elementSelector) or
        //          GroupBy<T, TKey, TResult>(keySelector, resultSelector)
        // Arity 4: GroupBy<T, TKey, TElement, TResult>(keySelector, elementSelector, resultSelector)
        if (inv.ArgumentList.Arguments.Count < 2) return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam2) return null;

        if (typeArgs.Length == 3)
        {
            // Two lambdas at [0] and [1]
            var keyFqn = typeArgs[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var thirdFqn = typeArgs[2].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // Determine if this is element-selector or result-selector by checking 2nd lambda arity.
            var methodSym = (IMethodSymbol)model.GetSymbolInfo(inv).Symbol!;
            var secondFuncType = (INamedTypeSymbol)methodSym.Parameters[1].Type;
            var isElementSelector = secondFuncType.TypeArguments.Length == 2; // Func<T, TElement>

            var delegateFqn1 = $"global::System.Func<{elemFqn}, {keyFqn}>";
            var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_");
            if (emitResult1 is null) return null;
            allStaticFields.AddRange(emitResult1.StaticFields);

            string delegateFqn2;
            if (isElementSelector)
                delegateFqn2 = $"global::System.Func<{elemFqn}, {thirdFqn}>";
            else
                delegateFqn2 = $"global::System.Func<{keyFqn}, global::System.Collections.Generic.IEnumerable<{elemFqn}>, {thirdFqn}>";

            var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_");
            if (emitResult2 is null) return null;
            allStaticFields.AddRange(emitResult2.StaticFields);

            if (isElementSelector)
            {
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<{{keyFqn}}, {{thirdFqn}}>> {{MethodId("GroupBy", idx)}}(
                            this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                            global::System.Func<{{elemFqn}}, {{keyFqn}}> _1,
                            global::System.Func<{{elemFqn}}, {{thirdFqn}}> _2)
                        {
                {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                global::System.Linq.Queryable.GroupBy(
                                    (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                    __lambda1,
                                    __lambda2));
                        }

                """;
            }
            else
            {
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<{{thirdFqn}}> {{MethodId("GroupBy", idx)}}(
                            this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                            global::System.Func<{{elemFqn}}, {{keyFqn}}> _1,
                            global::System.Func<{{keyFqn}}, global::System.Collections.Generic.IEnumerable<{{elemFqn}}>, {{thirdFqn}}> _2)
                        {
                {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                global::System.Linq.Queryable.GroupBy(
                                    (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                    __lambda1,
                                    __lambda2));
                        }

                """;
            }
        }

        // Arity 4: GroupBy<T, TKey, TElement, TResult>(keySelector, elementSelector, resultSelector)
        if (typeArgs.Length == 4)
        {
            if (inv.ArgumentList.Arguments.Count < 3) return null;
            if (inv.ArgumentList.Arguments[2].Expression is not LambdaExpressionSyntax lam3) return null;

            var keyFqn = typeArgs[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var elemSelFqn = typeArgs[2].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var resultFqn = typeArgs[3].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var delegateFqn1 = $"global::System.Func<{elemFqn}, {keyFqn}>";
            var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_");
            if (emitResult1 is null) return null;
            allStaticFields.AddRange(emitResult1.StaticFields);

            var delegateFqn2 = $"global::System.Func<{elemFqn}, {elemSelFqn}>";
            var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_");
            if (emitResult2 is null) return null;
            allStaticFields.AddRange(emitResult2.StaticFields);

            var delegateFqn3 = $"global::System.Func<{keyFqn}, global::System.Collections.Generic.IEnumerable<{elemSelFqn}>, {resultFqn}>";
            var emitResult3 = EmitLambdaBody(lam3, elemSym, model, spc, globalOptions, delegateFqn3, "__lambda3", fieldPrefix: $"i{idx}c_");
            if (emitResult3 is null) return null;
            allStaticFields.AddRange(emitResult3.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("GroupBy", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{keyFqn}}> _1,
                        global::System.Func<{{elemFqn}}, {{elemSelFqn}}> _2,
                        global::System.Func<{{keyFqn}}, global::System.Collections.Generic.IEnumerable<{{elemSelFqn}}>, {{resultFqn}}> _3)
                    {
            {{emitResult1.Body}}{{emitResult2.Body}}{{emitResult3.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda1,
                                __lambda2,
                                __lambda3));
                    }

            """;
        }

        return null;
    }

    /// <summary>
    /// Emitter for Join (and LeftJoin/RightJoin) with 3 lambdas and 1 forwarded IEnumerable argument.
    /// </summary>
    private static string? EmitJoin(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn,
        ImmutableArray<ITypeSymbol> typeArgs,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        // Arguments: [0] inner, [1] outerKeySelector, [2] innerKeySelector, [3] resultSelector
        if (inv.ArgumentList.Arguments.Count < 4) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[2].Expression is not LambdaExpressionSyntax lam2) return null;
        if (inv.ArgumentList.Arguments[3].Expression is not LambdaExpressionSyntax lam3) return null;

        var innerType = typeArgs[1];
        var keyType = typeArgs[2];
        var resultType = typeArgs[3];
        var innerFqn = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var keyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Lambda 1: outerKeySelector — Func<T, TKey>
        var delegateFqn1 = $"global::System.Func<{elemFqn}, {keyFqn}>";
        var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_");
        if (emitResult1 is null) return null;
        allStaticFields.AddRange(emitResult1.StaticFields);

        // Lambda 2: innerKeySelector — Func<TInner, TKey>
        // Note: element type for this lambda is TInner, not T
        if (innerType is not INamedTypeSymbol innerSym) return null;
        var delegateFqn2 = $"global::System.Func<{innerFqn}, {keyFqn}>";
        var emitResult2 = EmitLambdaBody(lam2, innerSym, model, spc, globalOptions, delegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_");
        if (emitResult2 is null) return null;
        allStaticFields.AddRange(emitResult2.StaticFields);

        // Lambda 3: resultSelector — Func<T, TInner, TResult>
        // Use the stub's parameter type for the result selector delegate FQN.
        var resultSelectorParam = model.GetSymbolInfo(inv).Symbol is IMethodSymbol m && m.Parameters.Length > 3
            ? m.Parameters[3].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : $"global::System.Func<{elemFqn}, {innerFqn}, {resultFqn}>";
        var emitResult3 = EmitLambdaBody(lam3, elemSym, model, spc, globalOptions, resultSelectorParam, "__lambda3", fieldPrefix: $"i{idx}c_");
        if (emitResult3 is null) return null;
        allStaticFields.AddRange(emitResult3.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId(methodName, idx)}}(
                    this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                    global::System.Collections.Generic.IEnumerable<{{innerFqn}}> inner,
                    global::System.Func<{{elemFqn}}, {{keyFqn}}> _1,
                    global::System.Func<{{innerFqn}}, {{keyFqn}}> _2,
                    {{resultSelectorParam}} _3)
                {
        {{emitResult1.Body}}{{emitResult2.Body}}{{emitResult3.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                        global::System.Linq.Queryable.{{methodName}}(
                            (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                            inner,
                            __lambda1,
                            __lambda2,
                            __lambda3));
                }

        """;
    }

    /// <summary>
    /// Emitter for GroupJoin with 3 lambdas and 1 forwarded IEnumerable argument.
    /// Same as Join but resultSelector is Func&lt;T, IEnumerable&lt;TInner&gt;, TResult&gt;.
    /// </summary>
    private static string? EmitGroupJoin(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ImmutableArray<ITypeSymbol> typeArgs,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        // Delegate to EmitJoin — the method name is "GroupJoin" and the result selector shape
        // differs, but the generated code structure is identical.
        return EmitJoin(inv, model, spc, interceptAttr, idx, "GroupJoin", elemSym, elemFqn, typeArgs, globalOptions, allStaticFields);
    }

    /// <summary>
    /// Generic single-lambda emitter for user-defined stubs and future LINQ operators.
    /// Convention: the interceptor calls <c>Queryable.{methodName}</c> with the same name.
    /// The return type is taken from the stub's declared return type.
    /// Supports methods where the Func&lt;&gt; parameter is not necessarily at position 0
    /// (e.g., ExceptBy, Zip where the first parameter is IEnumerable&lt;T&gt;).
    /// Non-lambda parameters are forwarded directly to the Queryable.* call.
    /// </summary>
    private static string? EmitGenericSingleLambda(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn,
        IMethodSymbol method, int funcParamIndex,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[funcParamIndex].Expression is not LambdaExpressionSyntax lam) return null;

        // Build the full Func<…> type string from the Func<> parameter.
        var funcTypeArgs = ((INamedTypeSymbol)method.Parameters[funcParamIndex].Type).TypeArguments;
        var hasAnyAnon = funcTypeArgs.Any(t => IsAnonymousType(t));

        // Determine if the stub returns IRewritableQueryable<X> (queryable) or a scalar type.
        var isRewritableReturn = method.ReturnType is INamedTypeSymbol rqType
            && rqType.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName;

        ITypeSymbol? returnElemType = null;
        if (isRewritableReturn)
        {
            returnElemType = ((INamedTypeSymbol)method.ReturnType).TypeArguments[0];
            hasAnyAnon = hasAnyAnon || IsAnonymousType(returnElemType);
        }

        // For scalar returns, the FQN of the return type itself.
        var scalarReturnFqn = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // ThenBy/ThenByDescending require IOrderedQueryable<T>.
        var isOrdered = methodName is "ThenBy" or "ThenByDescending";
        var castFqn = isOrdered
            ? $"global::System.Linq.IOrderedQueryable<{elemFqn}>"
            : $"global::System.Linq.IQueryable<{elemFqn}>";

        // Build parameter list and Queryable argument list, forwarding non-lambda args.
        // interceptorParams: the parameter declarations for the generated method
        // queryableArgs: the arguments passed to Queryable.Method(source, ...)
        var interceptorParams = new List<string>();
        var queryableArgs = new List<string>();
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            var paramType = method.Parameters[i].Type;
            var paramTypeFqn = paramType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (i == funcParamIndex)
            {
                // This is the Func<> parameter — will be rewritten to an expression tree.
                // Use placeholder name "_" in the interceptor (it's unused at runtime).
                interceptorParams.Add($"{paramTypeFqn} _");
                queryableArgs.Add("__lambda");
            }
            else
            {
                // Non-lambda parameter — forward directly.
                var paramName = method.Parameters[i].Name;
                interceptorParams.Add($"{paramTypeFqn} {paramName}");
                queryableArgs.Add(paramName);
            }
        }
        var interceptorParamList = string.Join(",\n                    ", interceptorParams);
        var queryableArgList = string.Join(",\n                        ", queryableArgs);

        if (!hasAnyAnon)
        {
            var funcFqn = "global::System.Func<" +
                string.Join(", ", funcTypeArgs.Select(t =>
                    t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";
            var delegateFqn = funcFqn;
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            if (isRewritableReturn)
            {
                var returnElemFqn = returnElemType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $$"""
                        {{interceptAttr}}
                        internal static global::ExpressiveSharp.IRewritableQueryable<{{returnElemFqn}}> {{MethodId(methodName, idx)}}(
                            this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                            {{interceptorParamList}})
                        {
                {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                global::System.Linq.Queryable.{{methodName}}(
                                    ({{castFqn}})source,
                                    {{queryableArgList}}));
                        }

                """;
            }

            // Scalar return — call Queryable.Method directly without wrapping.
            return $$"""
                    {{interceptAttr}}
                    internal static {{scalarReturnFqn}} {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        {{interceptorParamList}})
                    {
            {{emitResult.Body}}            return global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})source,
                                {{queryableArgList}});
                    }

            """;
        }

        // Anonymous type detected — must match the full arity of method.TypeArguments.
        // All type args become generic params; concrete types use (object) casts in body.
        var methodTypeArgs = method.TypeArguments;
        var typeParamNames = new string[methodTypeArgs.Length];
        for (int i = 0; i < methodTypeArgs.Length; i++)
            typeParamNames[i] = $"T{i}";
        var typeParams = $"<{string.Join(", ", typeParamNames)}>";

        // Build generic Func<> — map each func type arg to its corresponding type param or concrete.
        // Since we're making all type params generic for arity matching, use T0 for elem, etc.
        var funcArgStrings = new string[funcTypeArgs.Length];
        for (int i = 0; i < funcTypeArgs.Length; i++)
            funcArgStrings[i] = $"T{i}";
        // Last func type arg might be the return position — map to corresponding method type param.
        var funcFqnGeneric = "global::System.Func<" + string.Join(", ", funcArgStrings) + ">";

        var returnParamName = typeParamNames.Length > 1 ? typeParamNames[typeParamNames.Length - 1] : "T0";

        // For the anon branch, build type aliases and delegate type using generic param names.
        var typeAliases = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        for (int i = 0; i < methodTypeArgs.Length; i++)
        {
            if (IsAnonymousType(methodTypeArgs[i]))
                typeAliases[methodTypeArgs[i]] = typeParamNames[i];
        }
        var anonFuncFqn = "global::System.Func<" +
            string.Join(", ", funcTypeArgs.Select((t, i) =>
                IsAnonymousType(t) ? funcArgStrings[i] : t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonFuncFqn, fieldPrefix: $"i{idx}_", typeAliases: typeAliases);
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        // Build anonymous-branch parameter and argument lists with forwarding.
        var anonInterceptorParams = new List<string>();
        var anonQueryableArgs = new List<string>();
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (i == funcParamIndex)
            {
                anonInterceptorParams.Add($"{funcFqnGeneric} _");
                anonQueryableArgs.Add("__lambda");
            }
            else
            {
                var paramType = method.Parameters[i].Type;
                var paramTypeFqn = paramType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var paramName = method.Parameters[i].Name;
                anonInterceptorParams.Add($"{paramTypeFqn} {paramName}");
                anonQueryableArgs.Add(paramName);
            }
        }
        var anonInterceptorParamList = string.Join(",\n                    ", anonInterceptorParams);
        var anonQueryableArgList = string.Join(",\n                        ", anonQueryableArgs);

        if (isRewritableReturn)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{returnParamName}}> {{MethodId(methodName, idx)}}{{typeParams}}(
                        this global::ExpressiveSharp.IRewritableQueryable<T0> source,
                        {{anonInterceptorParamList}})
                    {
            {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{returnParamName}}>)(object)
                            global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                                global::System.Linq.Queryable.{{methodName}}(
                                    ({{castFqn}})(object)source,
                                    {{anonQueryableArgList}}));
                    }

            """;
        }

        // Scalar return with anonymous types — return directly without wrapping.
        return $$"""
                {{interceptAttr}}
                internal static {{returnParamName}} {{MethodId(methodName, idx)}}{{typeParams}}(
                    this global::ExpressiveSharp.IRewritableQueryable<T0> source,
                    {{anonInterceptorParamList}})
                {
        {{anonEmitResult.Body}}            return global::System.Linq.Queryable.{{methodName}}(
                            ({{castFqn}})(object)source,
                            {{anonQueryableArgList}});
                }

        """;
    }

    /// <summary>
    /// Returns true if <paramref name="type"/> is or implements <c>IRewritableQueryable&lt;T&gt;</c>.
    /// </summary>
    private static bool IsRewritableQueryable(INamedTypeSymbol type)
    {
        if (type.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName)
            return true;

        return type.AllInterfaces.Any(i =>
            i.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName);
    }

    /// <summary>
    /// Finds the <c>IRewritableQueryable&lt;T&gt;</c> interface on <paramref name="type"/>,
    /// or returns <paramref name="type"/> itself if it is <c>IRewritableQueryable&lt;T&gt;</c>.
    /// </summary>
    private static INamedTypeSymbol? GetRewritableQueryableInterface(INamedTypeSymbol type)
    {
        if (type.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName)
            return type;

        return type.AllInterfaces.FirstOrDefault(i =>
            i.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName);
    }
}
