using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using ExpressiveSharp.Generator.Infrastructure;
using ExpressiveSharp.Generator.Models;
using ExpressiveSharp.Generator.SyntaxRewriters;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator;

/// <summary>
/// Source generator that intercepts calls to <c>IRewritableQueryable&lt;T&gt;</c> extension methods
/// that take <c>Func&lt;T,…&gt;</c> delegates (instead of <c>Expression&lt;Func&lt;T,…&gt;&gt;</c>).
/// For each such call-site it emits a <c>[InterceptsLocation]</c> method that rewrites the
/// lambda body through <see cref="ExpressionSyntaxRewriter"/> and forwards the result to the
/// matching <c>Queryable.*</c> overload.
///
/// Any extension method on <c>IRewritableQueryable&lt;T&gt;</c> that takes a <c>Func&lt;&gt;</c> is
/// intercepted by convention — including library-provided stubs and user-defined ones.
/// </summary>
[Generator]
public class PolyfillInterceptorGenerator : IIncrementalGenerator
{
    private const string IRewritableQueryableOpenTypeName =
        "ExpressiveSharp.IRewritableQueryable<T>";

    private const string PolyfillTypeName = "ExpressiveSharp.ExpressionPolyfill";
    private const string PolyfillMethodName = "Create";

    // ── IIncrementalGenerator ────────────────────────────────────────────────

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Syntactic pre-filter: any member-access invocation with at least one argument
        // is a candidate. The semantic check in Emit does the real filtering.
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is InvocationExpressionSyntax inv &&
                inv.Expression is MemberAccessExpressionSyntax &&
                inv.ArgumentList.Arguments.Count > 0,
            transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node);

        var globalOptions = context.AnalyzerConfigOptionsProvider
            .Select(static (opts, _) => new ExpressiveGlobalOptions(opts.GlobalOptions));

        // Combine with the full compilation so we can do semantic analysis in the output step.
        context.RegisterSourceOutput(
            candidates.Collect().Combine(context.CompilationProvider).Combine(globalOptions),
            static (spc, pair) => Emit(pair.Left.Left, pair.Left.Right, pair.Right, spc));
    }

    // ── Emission ─────────────────────────────────────────────────────────────

    private static void Emit(
        ImmutableArray<InvocationExpressionSyntax> invocations,
        Compilation compilation,
        ExpressiveGlobalOptions globalOptions,
        SourceProductionContext spc)
    {
        var methodsBuilder = new StringBuilder();
        var allStaticFields = new List<string>();
        var snippetCount = 0;

        foreach (var inv in invocations)
        {
            spc.CancellationToken.ThrowIfCancellationRequested();

            try
            {
                var snippet = TryEmitPolyfill(inv, compilation, spc, snippetCount, globalOptions, allStaticFields)
                           ?? TryEmit(inv, compilation, spc, snippetCount, globalOptions, allStaticFields);
                if (snippet is not null)
                {
                    methodsBuilder.Append(snippet);
                    snippetCount++;
                }
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                // Report the failure so it doesn't hide bugs silently.
                // The stub body will throw UnreachableException at runtime with a clear message.
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.InterceptorEmissionFailed,
                    inv.GetLocation(),
                    ex.GetType().Name + ": " + ex.Message));
            }
        }

        if (snippetCount == 0) return;

        var staticFieldsBuilder = new StringBuilder();
        if (allStaticFields.Count > 0)
        {
            foreach (var f in allStaticFields)
            {
                staticFieldsBuilder.Append("        ").AppendLine(f);
            }
            staticFieldsBuilder.AppendLine();
        }
        var staticFieldsBlock = staticFieldsBuilder.ToString();
        var methods = methodsBuilder.ToString();
        var source = $$"""
            // <auto-generated/>
            #nullable disable

            namespace ExpressiveSharp.Generated.Interceptors
            {
                internal static class PolyfillInterceptors
                {
            {{staticFieldsBlock}}{{methods}}    }
            }

            namespace System.Runtime.CompilerServices
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data) { }
                }
            }
            """;

        spc.AddSource("PolyfillInterceptors.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    // ── ExpressionPolyfill.Create() interception ──────────────────────────

    /// <summary>
    /// Detects calls to <c>ExpressionPolyfill.Polyfill&lt;TDelegate&gt;(lambda)</c> and emits
    /// an interceptor that returns a literal <c>Expression&lt;TDelegate&gt;</c> with the
    /// rewritten lambda body.
    /// </summary>
    private static string? TryEmitPolyfill(
        InvocationExpressionSyntax inv,
        Compilation compilation,
        SourceProductionContext spc,
        int index,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        var model = compilation.GetSemanticModel(inv.SyntaxTree);

        if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol method)
            return null;

        // Must be ExpressionPolyfill.Create<TDelegate>(...)
        if (method.Name != PolyfillMethodName)
            return null;
        if (method.ContainingType?.ToDisplayString() != PolyfillTypeName)
            return null;
        if (method.TypeArguments.Length != 1)
            return null;

        // First argument must be a lambda; optional second is params transformers
        if (inv.ArgumentList.Arguments.Count < 1)
            return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam)
            return null;
        var hasTransformers = method.Parameters.Length == 2;

        var interceptableLocation = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptableLocation(
            model, inv, spc.CancellationToken);
        if (interceptableLocation is null)
            return null;
        var interceptAttr = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(interceptableLocation);

        // Extract the delegate type — e.g., Func<Order, bool>
        var delegateType = method.TypeArguments[0];
        var delegateFqn = delegateType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Default to Rewrite (the whole point of Polyfill is enabling expression tree features),
        // but allow MSBuild global property to override.
        

        // Get the parameter types from the delegate to build Expression<TDelegate>
        // For Func<T1, T2, ..., TResult>, the lambda parameters map to T1..Tn
        if (delegateType is not INamedTypeSymbol delegateNamed || delegateNamed.TypeArguments.IsEmpty)
            return null;

        // Use the first type argument as the "element" type for the rewriter
        var elemType = delegateNamed.TypeArguments[0];
        if (elemType is not INamedTypeSymbol elemSymbol)
            return null;

        // Use ExpressionTreeEmitter to build the expression tree
        var exprTypeFqn = $"global::System.Linq.Expressions.Expression<{delegateFqn}>";
        var emitResult = EmitLambdaBody(lam, elemSymbol, model, spc, globalOptions, delegateFqn,
            fieldPrefix: $"i{index}_");
        if (emitResult is null)
            return null;

        allStaticFields.AddRange(emitResult.StaticFields);

        if (hasTransformers)
        {
            return $$"""
                    {{interceptAttr}}
                    internal static global::System.Linq.Expressions.Expression<{{delegateFqn}}> {{MethodId("Create", index)}}(
                        {{delegateFqn}} _,
                        params global::ExpressiveSharp.IExpressionTreeTransformer[] transformers)
                    {
            {{emitResult.Body}}            global::System.Linq.Expressions.Expression result = __lambda;
                        foreach (var t in transformers) result = t.Transform(result);
                        return (global::System.Linq.Expressions.Expression<{{delegateFqn}}>)result;
                    }

            """;
        }

        return $$"""
                {{interceptAttr}}
                internal static global::System.Linq.Expressions.Expression<{{delegateFqn}}> {{MethodId("Create", index)}}(
                    {{delegateFqn}} _)
                {
        {{emitResult.Body}}            return __lambda;
                }

        """;
    }

    // ── Per-invocation dispatch (IRewritableQueryable) ───────────────────────

    private static string? TryEmit(
        InvocationExpressionSyntax inv,
        Compilation compilation,
        SourceProductionContext spc,
        int index,
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        var model = compilation.GetSemanticModel(inv.SyntaxTree);
        var ma = (MemberAccessExpressionSyntax)inv.Expression;

        // Receiver must be or implement IRewritableQueryable<T>.
        if (model.GetTypeInfo(ma.Expression).Type is not INamedTypeSymbol receiverType)
            return null;

        // Check both the type itself and its implemented interfaces
        if (!IsRewritableQueryable(receiverType))
            return null;

        if (model.GetSymbolInfo(inv).Symbol is not IMethodSymbol method)
            return null;

        // The stub convention: the first non-receiver parameter must be a Func<> delegate,
        // not an Expression<Func<>>. This distinguishes user/library IRewritableQueryable<T> stubs
        // from regular IQueryable<T> extension methods.
        if (method.Parameters.IsEmpty) return null;
        if (method.Parameters[0].Type is not INamedTypeSymbol firstParamType) return null;
        if (firstParamType.ConstructedFrom.Name != "Func" ||
            firstParamType.ConstructedFrom.ContainingNamespace?.ToDisplayString() != "System")
            return null;

        // Get the interceptable location using the Roslyn 5.0+ API.
        // This produces the correct [InterceptsLocation(version, data)] attribute text.
        var interceptableLocation = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptableLocation(
            model, inv, spc.CancellationToken);

        if (interceptableLocation is null)
            return null;

        var interceptAttr = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(interceptableLocation);

        // Element type T of IRewritableQueryable<T>.
        // The receiver may be IRewritableQueryable<T> directly, or a type that implements it.
        var rewritableInterface = GetRewritableQueryableInterface(receiverType);
        if (rewritableInterface is null)
            return null;
        var elementType = rewritableInterface.TypeArguments[0];
        if (elementType is not INamedTypeSymbol elementSymbol)
            return null; // Skip when T is itself a type parameter
        if (elementSymbol.IsAnonymousType)
            return null; // Anonymous element types can't be named in the interceptor body

        var elementFqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodName = ma.Name.Identifier.Text;
        var typeArgs = method.TypeArguments;

        // Per-call WithExpressionRewrite() → MSBuild global → hardcoded Ignore fallback.
        

        return methodName switch {
            "Where"
                when typeArgs.Length == 1
                => EmitWhere(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, globalOptions, allStaticFields),

            "Select"
                when typeArgs.Length == 2
                => EmitSelect(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, allStaticFields),

            "SelectMany"
                when typeArgs.Length == 2
                => EmitSelectMany2(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, allStaticFields),

            "SelectMany"
                when typeArgs.Length == 3
                => EmitSelectMany3(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], typeArgs[2], globalOptions, allStaticFields),

            "OrderBy" or "OrderByDescending"
                when typeArgs.Length == 2
                => EmitOrdering(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs[1], ordered: false, globalOptions, allStaticFields),

            "ThenBy" or "ThenByDescending"
                when typeArgs.Length == 2
                => EmitOrdering(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, typeArgs[1], ordered: true, globalOptions, allStaticFields),

            "GroupBy"
                when typeArgs.Length == 2
                => EmitGroupBy(inv, model, spc, interceptAttr, index, elementSymbol, elementFqn, typeArgs[1], globalOptions, allStaticFields),

            // Generic fallback: any user-defined or future single-lambda stub whose name
            // matches a Queryable.* method by convention.
            _ => EmitGenericSingleLambda(inv, model, spc, interceptAttr, index, methodName, elementSymbol, elementFqn, method, globalOptions, allStaticFields),
        };
    }

    // ── Lambda helpers ───────────────────────────────────────────────────────

    /// <summary>
    /// Uses <see cref="Emitter.ExpressionTreeEmitter"/> to build the expression tree for a lambda body.
    /// Returns the emitter result containing imperative Expression.* factory code, or null on failure.
    /// </summary>
    private static Emitter.EmitResult? EmitLambdaBody(
        LambdaExpressionSyntax lambda,
        INamedTypeSymbol elementSymbol,
        
        SemanticModel model,
        SourceProductionContext spc,
        ExpressiveGlobalOptions globalOptions,
        string delegateTypeFqn,
        string assignToVariable = "__lambda",
        string fieldPrefix = "")
    {
        if (lambda.Body is not SyntaxNode bodySyntax)
            return null;

        // For expression-bodied lambdas, use the expression directly.
        // For block-bodied lambdas, use the block.
        var bodyNode = lambda.Body is ExpressionSyntax expr ? (SyntaxNode)expr : lambda.Body;
        if (bodyNode is null) return null;

        var emitter = new Emitter.ExpressionTreeEmitter(model, spc, fieldPrefix);

        var emitterParams = new List<Emitter.EmitterParameter>();
        if (lambda is SimpleLambdaExpressionSyntax simple)
        {
            var paramSymbol = model.GetDeclaredSymbol(simple.Parameter);
            var paramTypeFqn = elementSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            emitterParams.Add(new Emitter.EmitterParameter(
                simple.Parameter.Identifier.Text, paramTypeFqn,
                symbol: paramSymbol as IParameterSymbol));
        }
        else if (lambda is ParenthesizedLambdaExpressionSyntax parens)
        {
            foreach (var param in parens.ParameterList.Parameters)
            {
                var paramSymbol = model.GetDeclaredSymbol(param) as IParameterSymbol;
                var paramTypeFqn = paramSymbol?.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "object";
                emitterParams.Add(new Emitter.EmitterParameter(
                    param.Identifier.Text, paramTypeFqn, symbol: paramSymbol));
            }
        }

        // Determine return type from delegate type args
        var returnTypeFqn = "object";
        if (elementSymbol.ContainingNamespace is not null)
        {
            // Try to get the return type from the lambda's actual type info
            var typeInfo = model.GetTypeInfo(lambda);
            if (typeInfo.ConvertedType is INamedTypeSymbol convertedType &&
                convertedType.TypeArguments.Length > 0)
            {
                returnTypeFqn = convertedType.TypeArguments[convertedType.TypeArguments.Length - 1]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
        }

        var result = emitter.Emit(bodyNode, emitterParams, returnTypeFqn, delegateTypeFqn,
            assignToVariable: assignToVariable);

        // Prepend source comment showing the original lambda
        var sourceText = lambda.NormalizeWhitespace().ToFullString()
            .Replace("\r", "").Replace("\n", " ");
        var commentLine = $"            // Source: {sourceText}\n";
        return new Emitter.EmitResult(commentLine + result.Body, result.StaticFields);
    }

    /// <summary>Returns the identifier text of the Nth parameter (0-based) of <paramref name="lambda"/>.</summary>
    private static string? ParamName(LambdaExpressionSyntax lambda, int index = 0) => lambda switch {
        SimpleLambdaExpressionSyntax s when index == 0 => s.Parameter.Identifier.Text,
        ParenthesizedLambdaExpressionSyntax p when p.ParameterList.Parameters.Count > index => p.ParameterList.Parameters[index].Identifier.Text,
        _ => null,
    };

    // ── Type helpers ─────────────────────────────────────────────────────────

    /// <summary>
    /// Returns true if <paramref name="type"/> is an anonymous type, which cannot be
    /// named in C# source and requires a generic type parameter in the interceptor signature.
    /// </summary>
    private static bool IsAnonymousType(ITypeSymbol type)
        => type is INamedTypeSymbol { IsAnonymousType: true };

    // ── Formatting helpers ───────────────────────────────────────────────────

    private static string MethodId(string op, int index) => $"__Polyfill_{op}_{index}";

    // ── Per-operator emitters ────────────────────────────────────────────────
    // Each emitter returns a source snippet (or null on failure) using $$"""...""" raw string
    // literals. With two dollar signs: single { } are literal C# braces; {{expr}} interpolates.

    private static string? EmitWhere(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, 
        ExpressiveGlobalOptions globalOptions, List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;
        var delegateFqn = $"global::System.Func<{elemFqn}, bool>";
        var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
        if (emitResult is null) return null;
        allStaticFields.AddRange(emitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> {{MethodId("Where", idx)}}(
                    this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                    global::System.Func<{{elemFqn}}, bool> _)
                {
        {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                        global::System.Linq.Queryable.Where(
                            (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                            __lambda));
                }

        """;
    }

    private static string? EmitSelect(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnon = IsAnonymousType(resultType);
        if (!isAnon)
        {
            var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = $"global::System.Func<{elemFqn}, {resultFqn}>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("Select", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{resultFqn}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Select(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda));
                    }

            """;
        }

        // Anonymous result type: must match arity 2 (T, TResult) of Select<T, TResult>.
        // TElem is generic in signature but concrete in body via (object) cast.
        var anonResultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, {anonResultFqn}>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_");
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("Select", idx)}}<TElem, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TResult> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.Select(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelectMany2(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnon = IsAnonymousType(resultType);
        if (!isAnon)
        {
            var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{resultFqn}>>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("SelectMany", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, global::System.Collections.Generic.IEnumerable<{{resultFqn}}>> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda));
                    }

            """;
        }

        var anonDelegateFqn = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_");
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("SelectMany", idx)}}<TElem, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, global::System.Collections.Generic.IEnumerable<TResult>> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitSelectMany3(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn,
        ITypeSymbol collType, ITypeSymbol resultType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments.Count < 2) return null;
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam1) return null;
        if (inv.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lam2) return null;

        var collFqn = collType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var hasAnon = IsAnonymousType(collType) || IsAnonymousType(resultType);
        if (!hasAnon)
        {
            var resultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn1 = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{collFqn}>>";
            var emitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, delegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_");
            if (emitResult1 is null) return null;
            allStaticFields.AddRange(emitResult1.StaticFields);

            var delegateFqn2 = $"global::System.Func<{elemFqn}, {collFqn}, {resultFqn}>";
            var emitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, delegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_");
            if (emitResult2 is null) return null;
            allStaticFields.AddRange(emitResult2.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{resultFqn}}> {{MethodId("SelectMany", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, global::System.Collections.Generic.IEnumerable<{{collFqn}}>> _1,
                        global::System.Func<{{elemFqn}}, {{collFqn}}, {{resultFqn}}> _2)
                    {
            {{emitResult1.Body}}{{emitResult2.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda1,
                                __lambda2));
                    }

            """;
        }

        // Arity 3: <TElem, TCollection, TResult>. All become generic to match SelectMany<T, TCollection, TResult>.
        var anonDelegateFqn1 = $"global::System.Func<{elemFqn}, global::System.Collections.Generic.IEnumerable<{collFqn}>>";
        var anonEmitResult1 = EmitLambdaBody(lam1, elemSym, model, spc, globalOptions, anonDelegateFqn1, "__lambda1", fieldPrefix: $"i{idx}a_");
        if (anonEmitResult1 is null) return null;
        allStaticFields.AddRange(anonEmitResult1.StaticFields);

        var anonResultFqn = resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var anonDelegateFqn2 = $"global::System.Func<{elemFqn}, {collFqn}, {anonResultFqn}>";
        var anonEmitResult2 = EmitLambdaBody(lam2, elemSym, model, spc, globalOptions, anonDelegateFqn2, "__lambda2", fieldPrefix: $"i{idx}b_");
        if (anonEmitResult2 is null) return null;
        allStaticFields.AddRange(anonEmitResult2.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TResult> {{MethodId("SelectMany", idx)}}<TElem, TCollection, TResult>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, global::System.Collections.Generic.IEnumerable<TCollection>> _1,
                    global::System.Func<TElem, TCollection, TResult> _2)
                {
        {{anonEmitResult1.Body}}{{anonEmitResult2.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TResult>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.SelectMany(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda1,
                                __lambda2));
                }

        """;
    }

    private static string? EmitOrdering(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol keyType,
         bool ordered, ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnonKey = IsAnonymousType(keyType);

        // ThenBy/ThenByDescending require IOrderedQueryable<T>; wrapper implements it.
        var castFqn = ordered
            ? $"global::System.Linq.IOrderedQueryable<{elemFqn}>"
            : $"global::System.Linq.IQueryable<{elemFqn}>";

        if (!isAnonKey)
        {
            var keyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = $"global::System.Func<{elemFqn}, {keyFqn}>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{keyFqn}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})source,
                                __lambda));
                    }

            """;
        }

        // Arity 2: <TElem, TKey>. Return type stays concrete (element type).
        var anonKeyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, {anonKeyFqn}>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_");
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<TElem> {{MethodId(methodName, idx)}}<TElem, TKey>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TKey> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<TElem>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})(object)source,
                                __lambda));
                }

        """;
    }

    private static string? EmitGroupBy(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        INamedTypeSymbol elemSym, string elemFqn, ITypeSymbol keyType,
         ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        var isAnonKey = IsAnonymousType(keyType);
        if (!isAnonKey)
        {
            var keyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var groupingFqn = $"global::System.Linq.IGrouping<{keyFqn}, {elemFqn}>";
            var delegateFqn = $"global::System.Func<{elemFqn}, {keyFqn}>";
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{groupingFqn}}> {{MethodId("GroupBy", idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        global::System.Func<{{elemFqn}}, {{keyFqn}}> _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)source,
                                __lambda));
                    }

            """;
        }

        // Arity 2: <TElem, TKey>. Return type is IGrouping<TKey, TElem>.
        var anonKeyFqn = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var anonDelegateFqn = $"global::System.Func<{elemFqn}, {anonKeyFqn}>";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonDelegateFqn, fieldPrefix: $"i{idx}_");
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<TKey, TElem>> {{MethodId("GroupBy", idx)}}<TElem, TKey>(
                    this global::ExpressiveSharp.IRewritableQueryable<TElem> source,
                    global::System.Func<TElem, TKey> _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<global::System.Linq.IGrouping<TKey, TElem>>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.GroupBy(
                                (global::System.Linq.IQueryable<{{elemFqn}}>)(object)source,
                                __lambda));
                }

        """;
    }

    /// <summary>
    /// Generic single-lambda emitter for user-defined stubs and future LINQ operators.
    /// Convention: the interceptor calls <c>Queryable.{methodName}</c> with the same name.
    /// The return type is taken from the stub's declared return type.
    /// </summary>
    private static string? EmitGenericSingleLambda(
        InvocationExpressionSyntax inv, SemanticModel model,
        SourceProductionContext spc, string interceptAttr, int idx,
        string methodName, INamedTypeSymbol elemSym, string elemFqn,
        IMethodSymbol method, 
        ExpressiveGlobalOptions globalOptions,
        List<string> allStaticFields)
    {
        if (inv.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lam) return null;

        // Build the full Func<…> type string from the method's first parameter.
        var funcTypeArgs = ((INamedTypeSymbol)method.Parameters[0].Type).TypeArguments;
        var hasAnyAnon = funcTypeArgs.Any(t => IsAnonymousType(t));

        // Return type comes from the stub's declared return type (must be IRewritableQueryable<X>).
        if (method.ReturnType is not INamedTypeSymbol returnType || returnType.TypeArguments.IsEmpty)
            return null;
        var returnElemType = returnType.TypeArguments[0];
        hasAnyAnon = hasAnyAnon || IsAnonymousType(returnElemType);

        // ThenBy/ThenByDescending require IOrderedQueryable<T>.
        var isOrdered = methodName is "ThenBy" or "ThenByDescending";
        var castFqn = isOrdered
            ? $"global::System.Linq.IOrderedQueryable<{elemFqn}>"
            : $"global::System.Linq.IQueryable<{elemFqn}>";

        if (!hasAnyAnon)
        {
            var funcFqn = "global::System.Func<" +
                string.Join(", ", funcTypeArgs.Select(t =>
                    t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";
            var returnElemFqn = returnElemType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var delegateFqn = funcFqn;
            var emitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, delegateFqn, fieldPrefix: $"i{idx}_");
            if (emitResult is null) return null;
            allStaticFields.AddRange(emitResult.StaticFields);

            return $$"""
                    {{interceptAttr}}
                    internal static global::ExpressiveSharp.IRewritableQueryable<{{returnElemFqn}}> {{MethodId(methodName, idx)}}(
                        this global::ExpressiveSharp.IRewritableQueryable<{{elemFqn}}> source,
                        {{funcFqn}} _)
                    {
            {{emitResult.Body}}            return global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})source,
                                __lambda));
                    }

            """;
        }

        // Anonymous type detected — must match the full arity of method.TypeArguments.
        // All type args become generic params; concrete types use (object) casts in body.
        var methodTypeArgs = method.TypeArguments;
        var typeParamNames = new string[methodTypeArgs.Length];
        for (int i = 0; i < methodTypeArgs.Length; i++)
            typeParamNames[i] = $"T{i}";
        var typeParams = $"<{string.Join(", ", typeParamNames)}>";

        // Build generic Func<> — map each func type arg to its corresponding type param or concrete.
        // Since we're making all type params generic for arity matching, use T0 for elem, etc.
        var funcArgStrings = new string[funcTypeArgs.Length];
        for (int i = 0; i < funcTypeArgs.Length; i++)
            funcArgStrings[i] = $"T{i}";
        // Last func type arg might be the return position — map to corresponding method type param.
        var funcFqnGeneric = "global::System.Func<" + string.Join(", ", funcArgStrings) + ">";

        var returnParamName = typeParamNames.Length > 1 ? typeParamNames[typeParamNames.Length - 1] : "T0";

        // For the anon branch, build the concrete delegate type for the emitter
        var anonFuncFqn = "global::System.Func<" +
            string.Join(", ", funcTypeArgs.Select(t =>
                t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) + ">";
        var anonEmitResult = EmitLambdaBody(lam, elemSym, model, spc, globalOptions, anonFuncFqn, fieldPrefix: $"i{idx}_");
        if (anonEmitResult is null) return null;
        allStaticFields.AddRange(anonEmitResult.StaticFields);

        return $$"""
                {{interceptAttr}}
                internal static global::ExpressiveSharp.IRewritableQueryable<{{returnParamName}}> {{MethodId(methodName, idx)}}{{typeParams}}(
                    this global::ExpressiveSharp.IRewritableQueryable<T0> source,
                    {{funcFqnGeneric}} _)
                {
        {{anonEmitResult.Body}}            return (global::ExpressiveSharp.IRewritableQueryable<{{returnParamName}}>)(object)
                        global::ExpressiveSharp.Extensions.ExpressionRewriteExtensions.WithExpressionRewrite(
                            global::System.Linq.Queryable.{{methodName}}(
                                ({{castFqn}})(object)source,
                                __lambda));
                }

        """;
    }

    /// <summary>
    /// Returns true if <paramref name="type"/> is or implements <c>IRewritableQueryable&lt;T&gt;</c>.
    /// </summary>
    private static bool IsRewritableQueryable(INamedTypeSymbol type)
    {
        if (type.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName)
            return true;

        return type.AllInterfaces.Any(i =>
            i.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName);
    }

    /// <summary>
    /// Finds the <c>IRewritableQueryable&lt;T&gt;</c> interface on <paramref name="type"/>,
    /// or returns <paramref name="type"/> itself if it is <c>IRewritableQueryable&lt;T&gt;</c>.
    /// </summary>
    private static INamedTypeSymbol? GetRewritableQueryableInterface(INamedTypeSymbol type)
    {
        if (type.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName)
            return type;

        return type.AllInterfaces.FirstOrDefault(i =>
            i.ConstructedFrom.ToDisplayString() == IRewritableQueryableOpenTypeName);
    }
}
