using System.Text;
using ExpressiveSharp.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator.Emitter;

/// <summary>
/// Emits the user-visible partial-class declaration with the synthesized property when
/// <c>[ExpressiveProperty]</c> is applied. The property caches materialized values (set by
/// projection middleware / EF Core / HotChocolate) and otherwise delegates to the stub for
/// the formula.
/// </summary>
static internal class SynthesizedPropertyEmitter
{
    public static void Emit(SynthesizedPropertySpec spec, string generatedFileName, SourceProductionContext context)
    {
        var source = BuildSource(spec);
        context.AddSource(generatedFileName, SourceText.From(source, Encoding.UTF8));
    }

    /// <summary>
    /// Produces the synthesized partial-class C# source as a string. Pure function of the spec —
    /// safe to call from incremental pipeline transforms (no <see cref="SourceProductionContext"/> required).
    /// </summary>
    public static string BuildSource(SynthesizedPropertySpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = spec.ContainingTypeNamespace is not null;
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {spec.ContainingTypeNamespace}");
            sb.AppendLine("{");
        }

        var baseIndent = hasNamespace ? "    " : "";
        var nestingDepth = spec.ContainingTypePath.Count;

        // Emit partial wrappers for any enclosing (nested) types, from outermost in.
        // Each level uses its actual type keyword so a struct/record container doesn't get
        // emitted as `partial class`.
        for (var i = 0; i < nestingDepth; i++)
        {
            var indent = baseIndent + new string(' ', i * 4);
            var name = spec.ContainingTypePath[i];
            var keyword = spec.ContainingTypeKeywords[i];
            sb.AppendLine($"{indent}partial {keyword} {name}");
            sb.AppendLine($"{indent}{{");
        }

        var memberIndent = baseIndent + new string(' ', nestingDepth * 4);
        var body = spec.UseTernaryShape ? BuildTernaryBody(spec, memberIndent) : BuildCoalesceBody(spec, memberIndent);
        sb.Append(body);

        for (var i = nestingDepth - 1; i >= 0; i--)
        {
            var indent = baseIndent + new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string BuildCoalesceBody(SynthesizedPropertySpec spec, string indent)
    {
        var stubCall = spec.StubIsMethod ? $"{spec.StubMemberName}()" : spec.StubMemberName;

        var sb = new StringBuilder();
        sb.AppendLine($"{indent}private {spec.BackingFieldTypeFqn} {spec.BackingFieldName};");
        sb.AppendLine($"{indent}public {spec.PropertyTypeFqn} {spec.PropertyName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => {spec.BackingFieldName} ?? {stubCall};");
        sb.AppendLine($"{indent}    init => {spec.BackingFieldName} = value;");
        sb.AppendLine($"{indent}}}");
        return sb.ToString();
    }

    private static string BuildTernaryBody(SynthesizedPropertySpec spec, string indent)
    {
        var stubCall = spec.StubIsMethod ? $"{spec.StubMemberName}()" : spec.StubMemberName;

        var sb = new StringBuilder();
        sb.AppendLine($"{indent}private {spec.BackingFieldTypeFqn} {spec.BackingFieldName};");
        sb.AppendLine($"{indent}private bool {spec.HasValueFlagName};");
        sb.AppendLine($"{indent}public {spec.PropertyTypeFqn} {spec.PropertyName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => {spec.HasValueFlagName} ? {spec.BackingFieldName} : {stubCall};");
        sb.AppendLine($"{indent}    init");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {spec.HasValueFlagName} = true;");
        sb.AppendLine($"{indent}        {spec.BackingFieldName} = value;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
        return sb.ToString();
    }
}
