using System.Text;
using ExpressiveSharp.Generator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator.Emitter;

/// <summary>
/// Emits the user-visible partial-class declaration with the synthesized property when
/// <c>[ExpressiveFor(..., Synthesize = true)]</c> is applied. The property caches materialized
/// values (set by projection middleware / EF Core / HotChocolate) and otherwise delegates to
/// the stub for the formula.
/// </summary>
static internal class SynthesizedPropertyEmitter
{
    public static void Emit(SynthesizedPropertySpec spec, string generatedFileName, SourceProductionContext context)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = spec.ContainingTypeNamespace is not null;
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {spec.ContainingTypeNamespace}");
            sb.AppendLine("{");
        }

        var baseIndent = hasNamespace ? "    " : "";
        var nestingDepth = spec.ContainingTypePath.Count;

        // Emit partial-class wrappers for any enclosing (nested) types, from outermost in.
        // The innermost is the type we attach the synthesized member to.
        for (var i = 0; i < nestingDepth; i++)
        {
            var indent = baseIndent + new string(' ', i * 4);
            var name = spec.ContainingTypePath[i];
            // Only the innermost knows its keyword; enclosing nests are "partial class" as a safe default.
            var keyword = i == nestingDepth - 1 ? spec.ContainingTypeKeyword : "class";
            sb.AppendLine($"{indent}partial {keyword} {name}");
            sb.AppendLine($"{indent}{{");
        }

        var memberIndent = baseIndent + new string(' ', nestingDepth * 4);
        var body = spec.UseTernaryShape ? BuildTernaryBody(spec, memberIndent) : BuildCoalesceBody(spec, memberIndent);
        sb.Append(body);

        for (var i = nestingDepth - 1; i >= 0; i--)
        {
            var indent = baseIndent + new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        context.AddSource(generatedFileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string BuildCoalesceBody(SynthesizedPropertySpec spec, string indent)
    {
        var fieldName = MakeBackingFieldName(spec.PropertyName);
        var stubCall = spec.StubIsMethod ? $"{spec.StubMemberName}()" : spec.StubMemberName;

        var sb = new StringBuilder();
        sb.AppendLine($"{indent}private {spec.BackingFieldTypeFqn} {fieldName};");
        sb.AppendLine($"{indent}public {spec.PropertyTypeFqn} {spec.PropertyName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => {fieldName} ?? {stubCall};");
        sb.AppendLine($"{indent}    init => {fieldName} = value;");
        sb.AppendLine($"{indent}}}");
        return sb.ToString();
    }

    private static string BuildTernaryBody(SynthesizedPropertySpec spec, string indent)
    {
        var fieldName = MakeBackingFieldName(spec.PropertyName);
        var flagName = MakeHasValueFlagName(spec.PropertyName);
        var stubCall = spec.StubIsMethod ? $"{spec.StubMemberName}()" : spec.StubMemberName;

        var sb = new StringBuilder();
        sb.AppendLine($"{indent}private {spec.BackingFieldTypeFqn} {fieldName};");
        sb.AppendLine($"{indent}private bool {flagName};");
        sb.AppendLine($"{indent}public {spec.PropertyTypeFqn} {spec.PropertyName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    get => {flagName} ? {fieldName} : {stubCall};");
        sb.AppendLine($"{indent}    init");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        {flagName} = true;");
        sb.AppendLine($"{indent}        {fieldName} = value;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");
        return sb.ToString();
    }

    private static string MakeBackingFieldName(string propertyName) =>
        "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);

    private static string MakeHasValueFlagName(string propertyName) =>
        "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1) + "HasValue";
}
