<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Basic.Reference.Assemblies.Net100" />

    <PackageReference Include="Microsoft.EntityFrameworkCore"
                      VersionOverride="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"
                      VersionOverride="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core"
                      VersionOverride="10.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"
                      VersionOverride="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ExpressiveSharp\ExpressiveSharp.csproj" />
    <ProjectReference Include="..\..\ExpressiveSharp.EntityFrameworkCore\ExpressiveSharp.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\ExpressiveSharp.Abstractions\ExpressiveSharp.Abstractions.csproj" />
    <ProjectReference Include="..\PlaygroundModel\ExpressiveSharp.Docs.PlaygroundModel.csproj" />
    <ProjectReference Include="..\..\ExpressiveSharp.Generator\ExpressiveSharp.Generator.csproj"
                      ReferenceOutputAssembly="true" />
  </ItemGroup>

</Project>
