using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator.Registry;

// Aggregates all expressive members into a single static dictionary keyed by
// System.RuntimeMethodHandle.Value (emitted as ExpressionRegistry.g.cs).
static internal class ExpressionRegistryEmitter
{
    public static void Emit(ImmutableArray<ExpressionRegistryEntry?> entries, SourceProductionContext context)
    {
        var allEntries = entries
            .Where(e => e is not null)
            .Select(e => e!)
            .ToList();

        if (allEntries.Count == 0)
        {
            return;
        }

        ReportDuplicateMappings(allEntries, context);

        EmitEditorBrowsablePartialFiles(allEntries, context);

        // Metadata-only entries (generic/extension classes) are not registry-eligible.
        var registryEntries = allEntries.Where(e => !e.IsMetadataOnly).ToList();

        if (registryEntries.Count == 0)
        {
            return;
        }

        var sw = new StringWriter();
        var writer = new IndentedTextWriter(sw, "    ");

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable disable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq.Expressions;");
        writer.WriteLine("using System.Reflection;");
        writer.WriteLine();
        writer.WriteLine("namespace ExpressiveSharp.Generated");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.WriteLine("internal static class ExpressionRegistry");
        writer.WriteLine("{");
        writer.Indent++;

        EmitBuildMethod(writer, registryEntries);
        writer.WriteLine();
        EmitMapField(writer);
        writer.WriteLine();
        EmitTryGetMethod(writer);
        writer.WriteLine();
        EmitRegisterHelper(writer);

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        context.AddSource("ExpressionRegistry.g.cs",
            SourceText.From(sw.ToString(), Encoding.UTF8));
    }

    private static void EmitBuildMethod(IndentedTextWriter writer, List<ExpressionRegistryEntry> entries)
    {
        writer.WriteLine("private static Dictionary<nint, LambdaExpression> Build()");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("const BindingFlags allFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;");
        writer.WriteLine("var map = new Dictionary<nint, LambdaExpression>();");
        writer.WriteLine();

        foreach (var entry in entries)
        {
            WriteRegistryEntryStatement(writer, entry);
        }

        writer.WriteLine();
        writer.WriteLine("return map;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void WriteRegistryEntryStatement(IndentedTextWriter writer, ExpressionRegistryEntry entry)
    {
        string? memberCallExpr = entry.MemberKind switch
        {
            ExpressionRegistryMemberType.Property =>
                $"typeof({entry.DeclaringTypeFullName}).GetProperty(\"{entry.MemberLookupName}\", allFlags)?.GetMethod",

            ExpressionRegistryMemberType.Method =>
                $"typeof({entry.DeclaringTypeFullName}).GetMethod(\"{entry.MemberLookupName}\", allFlags, null, {BuildTypeArrayExpr(entry.ParameterTypeNames)}, null)",

            ExpressionRegistryMemberType.Constructor =>
                $"typeof({entry.DeclaringTypeFullName}).GetConstructor(allFlags, null, {BuildTypeArrayExpr(entry.ParameterTypeNames)}, null)",

            _ => null
        };

        if (memberCallExpr is not null)
        {
            writer.WriteLine($"Register(map, {memberCallExpr}, \"{entry.GeneratedClassFullName}\", \"{entry.ExpressionMethodName}\");");
        }
    }

    // ResetMap is invoked by the hot-reload handler after a metadata update has patched
    // factory-method IL. `volatile` publishes the new Dictionary safely to concurrent readers.
    private static void EmitMapField(IndentedTextWriter writer)
    {
        writer.WriteLine("private static volatile Dictionary<nint, LambdaExpression> _map = Build();");
        writer.WriteLine();
        writer.WriteLine("internal static void ResetMap() => _map = Build();");
    }

    private static void EmitTryGetMethod(IndentedTextWriter writer)
    {
        writer.WriteLine("public static LambdaExpression TryGet(MemberInfo member)");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var handle = member switch");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("MethodInfo m      => (nint?)m.MethodHandle.Value,");
        writer.WriteLine("PropertyInfo p    => p.GetMethod?.MethodHandle.Value,");
        writer.WriteLine("ConstructorInfo c => (nint?)c.MethodHandle.Value,");
        writer.WriteLine("_                 => null");
        writer.Indent--;
        writer.WriteLine("};");
        writer.WriteLine();
        writer.WriteLine("return handle.HasValue && _map.TryGetValue(handle.Value, out var expr) ? expr : null;");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void EmitRegisterHelper(IndentedTextWriter writer)
    {
        writer.WriteLine("private static void Register(Dictionary<nint, LambdaExpression> map, MethodBase m, string exprClass, string exprMethodName)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("if (m is null) return;");
        writer.WriteLine("var exprType = m.DeclaringType?.Assembly.GetType(exprClass) ?? typeof(ExpressionRegistry).Assembly.GetType(exprClass);");
        writer.WriteLine(@"var exprMethod = exprType?.GetMethod(exprMethodName, BindingFlags.Static | BindingFlags.NonPublic);");
        writer.WriteLine("if (exprMethod is null) return;");
        writer.WriteLine("var expr = (LambdaExpression)exprMethod.Invoke(null, null)!;");
        writer.WriteLine();
        writer.WriteLine("// Apply declared transformers from the generated class (if any)");
        writer.WriteLine(@"const string expressionSuffix = ""_Expression"";");
        writer.WriteLine(@"if (exprMethodName.EndsWith(expressionSuffix, StringComparison.Ordinal))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine(@"var transformersSuffix = exprMethodName.Substring(0, exprMethodName.Length - expressionSuffix.Length) + ""_Transformers"";");
        writer.WriteLine(@"var transformersMethod = exprType.GetMethod(transformersSuffix, BindingFlags.Static | BindingFlags.NonPublic);");
        writer.WriteLine(@"if (transformersMethod?.Invoke(null, null) is global::ExpressiveSharp.IExpressionTreeTransformer[] transformers)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("Expression transformed = expr;");
        writer.WriteLine("foreach (var t in transformers) transformed = t.Transform(transformed);");
        writer.WriteLine("if (transformed is LambdaExpression lambdaResult) expr = lambdaResult;");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("map[m.MethodHandle.Value] = expr;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    private static string BuildTypeArrayExpr(ImmutableArray<string> parameterTypeNames)
    {
        if (parameterTypeNames.IsEmpty)
        {
            return "global::System.Type.EmptyTypes";
        }

        var typeofExprs = string.Join(", ", parameterTypeNames.Select(name => $"typeof({name})"));
        return $"new global::System.Type[] {{ {typeofExprs} }}";
    }

    // Emits one [EditorBrowsable(Never)] attribute-only partial class file per unique generated
    // class so the attribute appears exactly once, avoiding CS0579 across per-member partials.
    private static void EmitEditorBrowsablePartialFiles(List<ExpressionRegistryEntry> allEntries, SourceProductionContext context)
    {
        // First entry per class supplies the type parameter info.
        var seenClasses = new Dictionary<string, ExpressionRegistryEntry>();
        foreach (var entry in allEntries)
        {
            if (!seenClasses.ContainsKey(entry.GeneratedClassFullName))
            {
                seenClasses[entry.GeneratedClassFullName] = entry;
            }
        }

        foreach (var kvp in seenClasses)
        {
            var classFullName = kvp.Key;
            var entry = kvp.Value;

            var className = classFullName;
            var lastDot = classFullName.LastIndexOf('.');
            if (lastDot >= 0)
            {
                className = classFullName.Substring(lastDot + 1);
            }

            var typeParams = entry.ClassTypeParameters ?? "";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();
            sb.AppendLine("namespace ExpressiveSharp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    static partial class {className}{typeParams} {{ }}");
            sb.AppendLine("}");

            context.AddSource($"{className}.Attributes.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void ReportDuplicateMappings(List<ExpressionRegistryEntry> entries, SourceProductionContext context)
    {
        var duplicateGroups = entries
            .Where(e => e.StubLocation is not null)
            .GroupBy(e => e.GeneratedClassFullName + "." + e.ExpressionMethodName)
            .Where(g => g.Count() > 1);

        foreach (var group in duplicateGroups)
        {
            foreach (var entry in group)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Infrastructure.Diagnostics.ExpressiveForDuplicateMapping,
                    entry.StubLocation!.Value.ToLocation(),
                    entry.MemberLookupName,
                    entry.DeclaringTypeFullName));
            }
        }
    }
}
