using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ExpressiveSharp.Generator.Registry;

/// <summary>
/// Emits the <c>ExpressionRegistry.g.cs</c> source file that aggregates all expressive
/// members into a single static dictionary keyed by <see cref="System.RuntimeMethodHandle.Value"/>.
///
/// <para>
/// Code is generated using <see cref="IndentedTextWriter"/> rather than Roslyn's
/// <c>SyntaxFactory</c>: the output has a fixed template shape that never changes, so
/// string-based generation is simpler, more readable, and easier to maintain.
/// </para>
/// </summary>
static internal class ExpressionRegistryEmitter
{
    /// <summary>
    /// Builds and adds <c>ExpressionRegistry.g.cs</c> to the compilation output.
    /// The file is only emitted when at least one non-generic, non-extension expressive
    /// member is present (i.e. when <paramref name="entries"/> yields at least one representable entry).
    /// </summary>
    public static void Emit(ImmutableArray<ExpressionRegistryEntry?> entries, SourceProductionContext context)
    {
        var allEntries = entries
            .Where(e => e is not null)
            .Select(e => e!)
            .ToList();

        if (allEntries.Count == 0)
        {
            return;
        }

        // Report EXP0020 for duplicate [ExpressiveFor] mappings targeting the same member
        ReportDuplicateMappings(allEntries, context);

        // Emit [EditorBrowsable] attribute-only partial files for each unique generated class.
        EmitEditorBrowsablePartialFiles(allEntries, context);

        // Filter to registry-eligible entries (exclude metadata-only entries for generic/extension classes).
        var registryEntries = allEntries.Where(e => !e.IsMetadataOnly).ToList();

        if (registryEntries.Count == 0)
        {
            return;
        }

        // IndentedTextWriter wraps a TextWriter; keep a reference to the StringWriter
        // so we can read the result back with .ToString() after all writes are done.
        var sw = new StringWriter();
        var writer = new IndentedTextWriter(sw, "    ");

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable disable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq.Expressions;");
        writer.WriteLine("using System.Reflection;");
        writer.WriteLine();
        writer.WriteLine("namespace ExpressiveSharp.Generated");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.WriteLine("internal static class ExpressionRegistry");
        writer.WriteLine("{");
        writer.Indent++;

        EmitBuildMethod(writer, registryEntries);
        writer.WriteLine();
        EmitMapField(writer);
        writer.WriteLine();
        EmitTryGetMethod(writer);
        writer.WriteLine();
        EmitRegisterHelper(writer);

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        context.AddSource("ExpressionRegistry.g.cs",
            SourceText.From(sw.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emits the private <c>Build()</c> method that populates the runtime registry.
    /// Each expressive member is registered via the shared <c>Register(...)</c> helper to keep
    /// the method body compact — null-safety and the reflection lookup are handled once, centrally.
    /// </summary>
    private static void EmitBuildMethod(IndentedTextWriter writer, List<ExpressionRegistryEntry> entries)
    {
        writer.WriteLine("private static Dictionary<nint, LambdaExpression> Build()");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("const BindingFlags allFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;");
        writer.WriteLine("var map = new Dictionary<nint, LambdaExpression>();");
        writer.WriteLine();

        foreach (var entry in entries)
        {
            WriteRegistryEntryStatement(writer, entry);
        }

        writer.WriteLine();
        writer.WriteLine("return map;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits a single <c>Register(map, typeof(T).GetXxx(...), "ClassName")</c> call
    /// for one expressive entry inside <c>Build()</c>.
    /// </summary>
    private static void WriteRegistryEntryStatement(IndentedTextWriter writer, ExpressionRegistryEntry entry)
    {
        // Build the reflection-lookup expression for the member, switching on its kind.
        string? memberCallExpr = entry.MemberKind switch
        {
            // typeof(T).GetProperty("Name", allFlags)?.GetMethod
            ExpressionRegistryMemberType.Property =>
                $"typeof({entry.DeclaringTypeFullName}).GetProperty(\"{entry.MemberLookupName}\", allFlags)?.GetMethod",

            // typeof(T).GetMethod("Name", allFlags, null, new Type[] { typeof(P1), … }, null)
            ExpressionRegistryMemberType.Method =>
                $"typeof({entry.DeclaringTypeFullName}).GetMethod(\"{entry.MemberLookupName}\", allFlags, null, {BuildTypeArrayExpr(entry.ParameterTypeNames)}, null)",

            // typeof(T).GetConstructor(allFlags, null, new Type[] { typeof(P1), … }, null)
            ExpressionRegistryMemberType.Constructor =>
                $"typeof({entry.DeclaringTypeFullName}).GetConstructor(allFlags, null, {BuildTypeArrayExpr(entry.ParameterTypeNames)}, null)",

            _ => null
        };

        if (memberCallExpr is not null)
        {
            writer.WriteLine($"Register(map, {memberCallExpr}, \"{entry.GeneratedClassFullName}\", \"{entry.ExpressionMethodName}\");");
        }
    }

    /// <summary>
    /// Emits the <c>_map</c> field that lazily builds the registry once at class-load time:
    /// <c>private static readonly Dictionary&lt;nint, LambdaExpression&gt; _map = Build();</c>
    /// </summary>
    private static void EmitMapField(IndentedTextWriter writer)
    {
        writer.WriteLine("private static readonly Dictionary<nint, LambdaExpression> _map = Build();");
    }

    /// <summary>
    /// Emits the public <c>TryGet</c> method.
    /// It resolves the runtime <see cref="System.RuntimeMethodHandle.Value"/> for any
    /// <see cref="System.Reflection.MemberInfo"/> subtype via a switch expression,
    /// then looks it up in <c>_map</c>.
    /// </summary>
    private static void EmitTryGetMethod(IndentedTextWriter writer)
    {
        writer.WriteLine("public static LambdaExpression TryGet(MemberInfo member)");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var handle = member switch");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("MethodInfo m      => (nint?)m.MethodHandle.Value,");
        writer.WriteLine("PropertyInfo p    => p.GetMethod?.MethodHandle.Value,");
        writer.WriteLine("ConstructorInfo c => (nint?)c.MethodHandle.Value,");
        writer.WriteLine("_                 => null");
        writer.Indent--;
        writer.WriteLine("};");
        writer.WriteLine();
        writer.WriteLine("return handle.HasValue && _map.TryGetValue(handle.Value, out var expr) ? expr : null;");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits the private <c>Register</c> static helper shared by all per-entry calls in <c>Build()</c>.
    /// Centralises the null-check and the common reflection-to-expression lookup so that
    /// each entry only needs one compact call site.
    /// </summary>
    private static void EmitRegisterHelper(IndentedTextWriter writer)
    {
        writer.WriteLine("private static void Register(Dictionary<nint, LambdaExpression> map, MethodBase m, string exprClass, string exprMethodName)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("if (m is null) return;");
        writer.WriteLine("var exprType = m.DeclaringType?.Assembly.GetType(exprClass) ?? typeof(ExpressionRegistry).Assembly.GetType(exprClass);");
        writer.WriteLine(@"var exprMethod = exprType?.GetMethod(exprMethodName, BindingFlags.Static | BindingFlags.NonPublic);");
        writer.WriteLine("if (exprMethod is null) return;");
        writer.WriteLine("var expr = (LambdaExpression)exprMethod.Invoke(null, null)!;");
        writer.WriteLine();
        writer.WriteLine("// Apply declared transformers from the generated class (if any)");
        writer.WriteLine(@"const string expressionSuffix = ""_Expression"";");
        writer.WriteLine(@"if (exprMethodName.EndsWith(expressionSuffix, StringComparison.Ordinal))");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine(@"var transformersSuffix = exprMethodName.Substring(0, exprMethodName.Length - expressionSuffix.Length) + ""_Transformers"";");
        writer.WriteLine(@"var transformersMethod = exprType.GetMethod(transformersSuffix, BindingFlags.Static | BindingFlags.NonPublic);");
        writer.WriteLine(@"if (transformersMethod?.Invoke(null, null) is global::ExpressiveSharp.IExpressionTreeTransformer[] transformers)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("Expression transformed = expr;");
        writer.WriteLine("foreach (var t in transformers) transformed = t.Transform(transformed);");
        writer.WriteLine("if (transformed is LambdaExpression lambdaResult) expr = lambdaResult;");
        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("map[m.MethodHandle.Value] = expr;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Returns the C# expression for a <c>Type[]</c> used in reflection method/constructor lookups.
    /// Returns <c>global::System.Type.EmptyTypes</c> when <paramref name="parameterTypeNames"/> is empty.
    /// </summary>
    private static string BuildTypeArrayExpr(ImmutableArray<string> parameterTypeNames)
    {
        if (parameterTypeNames.IsEmpty)
        {
            return "global::System.Type.EmptyTypes";
        }

        var typeofExprs = string.Join(", ", parameterTypeNames.Select(name => $"typeof({name})"));
        return $"new global::System.Type[] {{ {typeofExprs} }}";
    }

    /// <summary>
    /// Emits a single <c>[EditorBrowsable(Never)]</c> attribute-only partial class file
    /// for each unique generated class. This ensures the attribute appears exactly once
    /// per class, avoiding CS0579 (duplicate attribute) across per-member partial files.
    /// </summary>
    private static void EmitEditorBrowsablePartialFiles(List<ExpressionRegistryEntry> allEntries, SourceProductionContext context)
    {
        // Group by class full name to emit one file per unique class.
        // Use the first entry per class to get type parameter info.
        var seenClasses = new Dictionary<string, ExpressionRegistryEntry>();
        foreach (var entry in allEntries)
        {
            if (!seenClasses.ContainsKey(entry.GeneratedClassFullName))
            {
                seenClasses[entry.GeneratedClassFullName] = entry;
            }
        }

        foreach (var kvp in seenClasses)
        {
            var classFullName = kvp.Key;
            var entry = kvp.Value;

            // Extract the simple class name from the full name (after the last '.')
            var className = classFullName;
            var lastDot = classFullName.LastIndexOf('.');
            if (lastDot >= 0)
            {
                className = classFullName.Substring(lastDot + 1);
            }

            var typeParams = entry.ClassTypeParameters ?? "";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();
            sb.AppendLine("namespace ExpressiveSharp.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"    static partial class {className}{typeParams} {{ }}");
            sb.AppendLine("}");

            context.AddSource($"{className}.Attributes.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    /// <summary>
    /// Reports EXP0020 on each stub when multiple [ExpressiveFor] stubs in the same project
    /// target the same member (same <see cref="ExpressionRegistryEntry.GeneratedClassFullName"/>).
    /// </summary>
    private static void ReportDuplicateMappings(List<ExpressionRegistryEntry> entries, SourceProductionContext context)
    {
        var duplicateGroups = entries
            .Where(e => e.StubLocation is not null)
            .GroupBy(e => e.GeneratedClassFullName + "." + e.ExpressionMethodName)
            .Where(g => g.Count() > 1);

        foreach (var group in duplicateGroups)
        {
            foreach (var entry in group)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    Infrastructure.Diagnostics.ExpressiveForDuplicateMapping,
                    entry.StubLocation!.Value.ToLocation(),
                    entry.MemberLookupName,
                    entry.DeclaringTypeFullName));
            }
        }
    }
}
